# BINARY FEATURES: Flag, Bool, True-False

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
!pip install missingno
import missingno as msno
from datetime import date
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import LocalOutlierFactor # çok değişkenli local outlier yaklama yöntemidir.
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, StandardScaler, RobustScaler

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.set_option('display.width', 500)

Requirement already satisfied: missingno in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (0.5.2)
Requirement already satisfied: numpy in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from missingno) (1.24.3)
Requirement already satisfied: matplotlib in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from missingno) (3.7.2)
Requirement already satisfied: scipy in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from missingno) (1.10.0)
Requirement already satisfied: seaborn in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from missingno) (0.12.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from matplotlib->missingno) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from matplotlib->missingno) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from matplotlib->missingno) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from matplotlib->missingno) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from matplotlib->missingno) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from matplotlib->missingno) (9.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from matplotlib->missingno) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from matplotlib->missingno) (2.8.2)
Requirement already satisfied: pandas>=0.25 in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from seaborn->missingno) (1.5.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from pandas>=0.25->seaborn->missingno) (2023.3.post1)
Requirement already satisfied: six>=1.5 in c:\users\ytaslioglu\appdata\local\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.16.0)

In [2]:
def load():
    df = pd.read_csv("titanic.csv")
    return df

In [3]:
#BU konuda genel kabul gören bir literatür yokur çünkü işlemden işleme değişmektedir.
#burada yapacak olduğumuz işlem 1 ve 0 üzerinden yeni değişkenler vermek olacak, 
df = load()

df.head()

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S

In [4]:
#öyle bir işlem yapmak istiyorum ki nan gördüğüm yerlere 1 nan olmayan yerlere 0 yazmak 
# istiyorum. normlade kabin değişkeni çöp bir değişken çünkü fazla sayıda nan değeri var.
#ancak ben bunları 1 ile doldurup bi bakayım diyorum gerçekten anlamsız bir değişken mi 
# bağımlı değişken ile aralarında hiçbir bağlantı var mı diyorum.

df["NEW_CABIN_BOOL"] = df["Cabin"].notnull().astype("int")
df #buardaki isimlendirmeye flag de yazabiliriz isimlendirme istediğimiz gibi olabilir

     PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch              Ticket    Fare            Cabin Embarked  NEW_CABIN_BOOL
0              1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0           A/5 21171   7.250              NaN        S               0
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0            PC 17599  71.283              C85        C               1
2              3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0    STON/O2. 3101282   7.925              NaN        S               0
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0              113803  53.100             C123        S               1
4              5         0       3                           Allen, Mr. William Henry    male 35.000      0      0              373450   8.050              NaN        S               0
5              6         0       3                                   Moran, Mr. James    male    NaN      0      0              330877   8.458              NaN        Q               0
6              7         0       1                            McCarthy, Mr. Timothy J    male 54.000      0      0               17463  51.862              E46        S               1
7              8         0       3                     Palsson, Master. Gosta Leonard    male  2.000      3      1              349909  21.075              NaN        S               0
8              9         1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female 27.000      0      2              347742  11.133              NaN        S               0
9             10         1       2                Nasser, Mrs. Nicholas (Adele Achem)  female 14.000      1      0              237736  30.071              NaN        C               0
10            11         1       3                    Sandstrom, Miss. Marguerite Rut  female  4.000      1      1             PP 9549  16.700               G6        S               1
11            12         1       1                           Bonnell, Miss. Elizabeth  female 58.000      0      0              113783  26.550             C103        S               1
12            13         0       3                     Saundercock, Mr. William Henry    male 20.000      0      0           A/5. 2151   8.050              NaN        S               0
13            14         0       3                        Andersson, Mr. Anders Johan    male 39.000      1      5              347082  31.275              NaN        S               0
14            15         0       3               Vestrom, Miss. Hulda Amanda Adolfina  female 14.000      0      0              350406   7.854              NaN        S               0
15            16         1       2                   Hewlett, Mrs. (Mary D Kingcome)   female 55.000      0      0              248706  16.000              NaN        S               0
16            17         0       3                               Rice, Master. Eugene    male  2.000      4      1              382652  29.125              NaN        Q               0
17            18         1       2                       Williams, Mr. Charles Eugene    male    NaN      0      0              244373  13.000              NaN        S               0
18            19         0       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female 31.000      1      0              345763  18.000              NaN        S               0
19            20         1       3                            Masselmani, Mrs. Fatima  female    NaN      0      0                2649   7.225              NaN        C               0
20            21         0       2                               Fynney, Mr. Joseph J    male 35.000      0      0              239865  26.000              NaN        S               0
21            22         1       2                              Beesley, Mr. Lawrence    male 34.000      0      0              248698  13.000              D56        S               1
22            23         1       3                        McGowan, Miss. Anna "Annie"  female 15.000      0      0              330923   8.029              NaN        Q               0
23            24         1       1                       Sloper, Mr. William Thompson    male 28.000      0      0              113788  35.500               A6        S               1
24            25         0       3                      Palsson, Miss. Torborg Danira  female  8.000      3      1              349909  21.075              NaN        S               0
25            26         1       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female 38.000      1      5              347077  31.387              NaN        S               0
26            27         0       3                            Emir, Mr. Farred Chehab    male    NaN      0      0                2631   7.225              NaN        C               0
27            28         0       1                     Fortune, Mr. Charles Alexander    male 19.000      3      2               19950 263.000      C23 C25 C27        S               1
28            29         1       3                      O'Dwyer, Miss. Ellen "Nellie"  female    NaN      0      0              330959   7.879              NaN        Q               0
29            30         0       3                                Todoroff, Mr. Lalio    male    NaN      0      0              349216   7.896              NaN        S               0
30            31         0       1                           Uruchurtu, Don. Manuel E    male 40.000      0      0            PC 17601  27.721              NaN        C               0
31            32         1       1     Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1      0            PC 17569 146.521              B78        C               1
32            33         1       3                           Glynn, Miss. Mary Agatha  female    NaN      0      0              335677   7.750              NaN        Q               0
33            34         0       2                              Wheadon, Mr. Edward H    male 66.000      0      0          C.A. 24579  10.500              NaN        S               0
34            35         0       1                            Meyer, Mr. Edgar Joseph    male 28.000      1      0            PC 17604  82.171              NaN        C               0
35            36         0       1                     Holverson, Mr. Alexander Oskar    male 42.000      1      0              113789  52.000              NaN        S               0
36            37         1       3                                   Mamee, Mr. Hanna    male    NaN      0      0                2677   7.229              NaN        C               0
37            38         0       3                           Cann, Mr. Ernest Charles    male 21.000      0      0          A./5. 2152   8.050              NaN        S               0
38            39         0       3                 Vander Planke, Miss. Augusta Maria  female 18.000      2      0              345764  18.000              NaN        S               0
39            40         1       3                        Nicola-Yarred, Miss. Jamila  female 14.000      1      0                2651  11.242              NaN        C               0
40            41         0       3     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female 40.000      1      0                7546   9.475              NaN        S               0
41            42         0       2  Turpin, Mrs. William John Robert (Dorothy Ann ...  female 27.000      1      0               11668  21.000              NaN        S               0
42            43         0       3                                Kraeff, Mr. Theodor    male    NaN      0      0              349253   7.896              NaN        C               0
43            44         1       2           Laroche, Miss. Simonne Marie Anne Andree  female  3.000      1      2       SC/Paris 2123  41.579              NaN        C               0
44            45         1       3                      Devaney, Miss. Margaret Delia  female 19.000      0      0              330958   7.879              NaN        Q               0
45            46         0       3                           Rogers, Mr. William John    male    NaN      0      0     S.C./A.4. 23567   8.050              NaN        S               0
46            47         0       3                                  Lennon, Mr. Denis    male    NaN      1      0              370371  15.500              NaN        Q               0
47            48         1       3                          O'Driscoll, Miss. Bridget  female    NaN      0      0               14311   7.750              NaN        Q               0
48            49         0       3                                Samaan, Mr. Youssef    male    NaN      2      0                2662  21.679              NaN        C               0
49            50         0       3      Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female 18.000      1      0              349237  17.800              NaN        S               0
50            51         0       3                         Panula, Master. Juha Niilo    male  7.000      4      1             3101295  39.688              NaN        S               0
51            52         0       3                       Nosworthy, Mr. Richard Cater    male 21.000      0      0          A/4. 39886   7.800              NaN        S               0
52            53         1       1           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female 49.000      1      0            PC 17572  76.729              D33        C               1
53            54         1       2  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female 29.000      1      0                2926  26.000              NaN        S               0
54            55         0       1                     Ostby, Mr. Engelhart Cornelius    male 65.000      0      1              113509  61.979              B30        C               1
55            56         1       1                                  Woolner, Mr. Hugh    male    NaN      0      0               19947  35.500              C52        S               1
56            57         1       2                                  Rugg, Miss. Emily  female 21.000      0      0          C.A. 31026  10.500              NaN        S               0
57            58         0       3                                Novel, Mr. Mansouer    male 28.500      0      0                2697   7.229              NaN        C               0
58            59         1       2                       West, Miss. Constance Mirium  female  5.000      1      2          C.A. 34651  27.750              NaN        S               0
59            60         0       3                 Goodwin, Master. William Frederick    male 11.000      5      2             CA 2144  46.900              NaN        S               0
60            61         0       3                              Sirayanian, Mr. Orsen    male 22.000      0      0                2669   7.229              NaN        C               0
61            62         1       1                                Icard, Miss. Amelie  female 38.000      0      0              113572  80.000              B28      NaN               1
62            63         0       1                        Harris, Mr. Henry Birkhardt    male 45.000      1      0               36973  83.475              C83        S               1
63            64         0       3                              Skoog, Master. Harald    male  4.000      3      2              347088  27.900              NaN        S               0
64            65         0       1                              Stewart, Mr. Albert A    male    NaN      0      0            PC 17605  27.721              NaN        C               0
65            66         1       3                           Moubarek, Master. Gerios    male    NaN      1      1                2661  15.246              NaN        C               0
66            67         1       2                       Nye, Mrs. (Elizabeth Ramell)  female 29.000      0      0          C.A. 29395  10.500              F33        S               1
67            68         0       3                           Crease, Mr. Ernest James    male 19.000      0      0           S.P. 3464   8.158              NaN        S               0
68            69         1       3                    Andersson, Miss. Erna Alexandra  female 17.000      4      2             3101281   7.925              NaN        S               0
69            70         0       3                                  Kink, Mr. Vincenz    male 26.000      2      0              315151   8.662              NaN        S               0
70            71         0       2                         Jenkin, Mr. Stephen Curnow    male 32.000      0      0          C.A. 33111  10.500              NaN        S               0
71            72         0       3                         Goodwin, Miss. Lillian Amy  female 16.000      5      2             CA 2144  46.900              NaN        S               0
72            73         0       2                               Hood, Mr. Ambrose Jr    male 21.000      0      0        S.O.C. 14879  73.500              NaN        S               0
73            74         0       3                        Chronopoulos, Mr. Apostolos    male 26.000      1      0                2680  14.454              NaN        C               0
74            75         1       3                                      Bing, Mr. Lee    male 32.000      0      0                1601  56.496              NaN        S               0
75            76         0       3                            Moen, Mr. Sigurd Hansen    male 25.000      0      0              348123   7.650            F G73        S               1
76            77         0       3                                  Staneff, Mr. Ivan    male    NaN      0      0              349208   7.896              NaN        S               0
77            78         0       3                           Moutal, Mr. Rahamin Haim    male    NaN      0      0              374746   8.050              NaN        S               0
78            79         1       2                      Caldwell, Master. Alden Gates    male  0.830      0      2              248738  29.000              NaN        S               0
79            80         1       3                           Dowdell, Miss. Elizabeth  female 30.000      0      0              364516  12.475              NaN        S               0
80            81         0       3                               Waelens, Mr. Achille    male 22.000      0      0              345767   9.000              NaN        S               0
81            82         1       3                        Sheerlinck, Mr. Jan Baptist    male 29.000      0      0              345779   9.500              NaN        S               0
82            83         1       3                     McDermott, Miss. Brigdet Delia  female    NaN      0      0              330932   7.787              NaN        Q               0
83            84         0       1                            Carrau, Mr. Francisco M    male 28.000      0      0              113059  47.100              NaN        S               0
84            85         1       2                                Ilett, Miss. Bertha  female 17.000      0      0          SO/C 14885  10.500              NaN        S               0
85            86         1       3  Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  female 33.000      3      0             3101278  15.850              NaN        S               0
86            87         0       3                             Ford, Mr. William Neal    male 16.000      1      3          W./C. 6608  34.375              NaN        S               0
87            88         0       3                      Slocovski, Mr. Selman Francis    male    NaN      0      0     SOTON/OQ 392086   8.050              NaN        S               0
88            89         1       1                         Fortune, Miss. Mabel Helen  female 23.000      3      2               19950 263.000      C23 C25 C27        S               1
89            90         0       3                             Celotti, Mr. Francesco    male 24.000      0      0              343275   8.050              NaN        S               0
90            91         0       3                               Christmann, Mr. Emil    male 29.000      0      0              343276   8.050              NaN        S               0
91            92         0       3                         Andreasson, Mr. Paul Edvin    male 20.000      0      0              347466   7.854              NaN        S               0
92            93         0       1                        Chaffee, Mr. Herbert Fuller    male 46.000      1      0         W.E.P. 5734  61.175              E31        S               1
93            94         0       3                            Dean, Mr. Bertram Frank    male 26.000      1      2           C.A. 2315  20.575              NaN        S               0
94            95         0       3                                  Coxon, Mr. Daniel    male 59.000      0      0              364500   7.250              NaN        S               0
95            96         0       3                        Shorney, Mr. Charles Joseph    male    NaN      0      0              374910   8.050              NaN        S               0
96            97         0       1                          Goldschmidt, Mr. George B    male 71.000      0      0            PC 17754  34.654               A5        C               1
97            98         1       1                    Greenfield, Mr. William Bertram    male 23.000      0      1            PC 17759  63.358          D10 D12        C               1
98            99         1       2               Doling, Mrs. John T (Ada Julia Bone)  female 34.000      0      1              231919  23.000              NaN        S               0
99           100         0       2                                  Kantor, Mr. Sinai    male 34.000      1      0              244367  26.000              NaN        S               0
100          101         0       3                            Petranec, Miss. Matilda  female 28.000      0      0              349245   7.896              NaN        S               0
101          102         0       3                   Petroff, Mr. Pastcho ("Pentcho")    male    NaN      0      0              349215   7.896              NaN        S               0
102          103         0       1                          White, Mr. Richard Frasar    male 21.000      0      1               35281  77.287              D26        S               1
103          104         0       3                         Johansson, Mr. Gustaf Joel    male 33.000      0      0                7540   8.654              NaN        S               0
104          105         0       3                     Gustafsson, Mr. Anders Vilhelm    male 37.000      2      0             3101276   7.925              NaN        S               0
105          106         0       3                              Mionoff, Mr. Stoytcho    male 28.000      0      0              349207   7.896              NaN        S               0
106          107         1       3                   Salkjelsvik, Miss. Anna Kristine  female 21.000      0      0              343120   7.650              NaN        S               0

In [5]:
#şimdi bağımlı değişkenim surviveda göre ortalama alacağım

df.groupby("NEW_CABIN_BOOL").agg({"Survived": "mean"})

# dikkat kabin numarası dolu olanların hayatta kalma oranı kabini boş olanların hayatta kalma oranına göre daha yüksek
#benim için başta çöp olan değişken aslında şu an benim için en önemli değişkenlerden biri oldu.

                Survived
NEW_CABIN_BOOL
0                  0.300
1                  0.667

In [7]:
#şimdi burada istatistiki bir test yapacağım, iki grubun oranını kıyaslamak için
#bu değişkenler birbiri ile ilişkili mi değil mi diye, elimde yeni oluşturduğum bir değişken var
#ve bu değişkenin bağımlı değişken ile bir ilişkisi var mı bunu merak ediyorum.

#bunun için oran testi yapıyorum.

from statsmodels.stats.proportion import proportions_ztest

test_stat, pvalue = proportions_ztest(count=[df.loc[df["NEW_CABIN_BOOL"] == 1, "Survived"].sum(),
                                            df.loc[df["NEW_CABIN_BOOL"] == 0, "Survived"].sum()],
                                      
                                      nobs=[df.loc[df["NEW_CABIN_BOOL"] == 1, "Survived"].shape[0],
                                           df.loc[df["NEW_CABIN_BOOL"] == 0, "Survived"].shape[0]])

print('Test Stat = %.4f, p-value = %.4f' % (test_stat, pvalue))

# burada kabin numarası 1 olanlar yani kabin numarası olanların toplamını aldım,
# sonra kabin nuaası olmayanlaro topladım, oran testini yapmak için iki parammetre var birincisi başarı sayısı ikincisi gözlem sayısı
# gözlem sayısı oran dolayısıyla kabin numarası olanlar için problem nedir hayatta kalmaktır.nobsta kabin numarası olanlar ve olmayanlar kaç kişi diye sordum
#bunları da nobs argumanına girdim, dikkat propotions z testinin sonuçları şu şekildedir,
# p1 ve p2 oranları arasında fark yoktur der, p1 ve p2 oranları neyi ifade eder? kabin numarası olanlar ve olmayanların hayatta kalıp kalmama durumunu ifade etmektedir.
#ikisi arasında fark yoktur diyen h0 hipotezi p value değeri 0.05ten küçük olduğundan dolayı reddedilir.yani aralarında istatistiki olarak anlamlı bir fark gibi gözüküyor,
# bir değişken türettik, başta benim için anlamlı olur mu olmaz mı bilmiyorum, modelleme yapmadan tam anlamıyla bunu göremem ama bana bir fikir vermesi açısından bu oranlar frekanslar da bunun dağılımı da 
#göz önünde bulundurulduğunda acaba birbirinden farklı mıdırı sordum ve farklıdır yanıtı geldi, dikkat çok değişkenli etkiyi bilmiyorum iki tane değişkeni saedce ikisi birlikte oluşmuş gibi değerlendirerek inceledim
#ama bu yapılar tek başına oluşmadı ki yani survived değişkeninin ortaya çıkışı burada ele aldığımız new cabin bool ile ortaya çıkmadı ki ama çıkmış olabilir bilmiyorum.
#şu andaki kanaatim çıkmış olabileceğine yönelik ama bilmiyorum, dolayısıyla neyi ifade etmeye çalışıyorum, çok değişkenli etkiyi bilmiyorum ben bu değişkenleri birlikte modele soktuğumda çokkdeğişkenli etkiyi gözlemleme imkanım olacak
#o durumda bu değişkenin anlamlı olup olmadığını daha iyi değerlendiriyor olacağım. newcabinbool değişkeninde ama şu anda ilerlemek ya da bu değişkeni kabul etmeye çalışmak için bir fikir edinmeye çalıştığımda 
#yeterli delili buldum. ancak tekrar dikka tçok değişkenli etkiyi bilmiyorum bunu test etmedim. doalyısıyla bu benim için çok önemli değişkendir genellemesini yapamıyorum.

Test Stat = 9.4597, p-value = 0.0000

bir iki tane daha binary feature oluşturuyorum

In [8]:
df.loc[((df['SibSp'] + df['Parch']) > 0), "NEW_IS_ALONE"] = "NO"
df.loc[((df['SibSp'] + df['Parch']) == 0), "NEW_IS_ALONE"] = "YES"
#sibspler yakın ve uzak olabilecek bir takım akrabalıkları ifade etmektedir.
#bunların toplamı eğer 0dan büyükse diyorum yeni bir değişken oluştur ve demek ki bu kişi yalnız değilmiş diyorum no yaz
#tam tersi eğer bunların toplamı 0a eşitse bu kişi yalnız olduğu için yes yazdır
#burada elimde iki adet değişken var bu iki değişkeni bir araya getirdim ve bunlara göre bir koşul oluşturdum.
#bu sayedde olası featureları türetmeye çalışıyorum, belki de kişi gemide tek olup olmamasına göre hayatta kalma refleksleri şekillenmiştir.
#neticesind bir sonuç çıkmayabilir de ancak deniyorum ve bunu suriveda gönderiyorum

In [9]:
df.groupby("NEW_IS_ALONE").agg({"Survived":"mean"})

              Survived
NEW_IS_ALONE
NO               0.506
YES              0.304

çıkan sonuca göre aralarında bir fark var gibi gözüküyor, yalnız olanların hayatta kalma oranı daha düşük gözüküyor, belki de çok değişkenli etkiden böyle oldu ancak bilmiyorum bir hipotez testi yapacağım. fark var gibi gözküyor ancak istatistiki olarak anlamlı bir fark mı bu diye bakacağım

In [10]:
from statsmodels.stats.proportion import proportions_ztest

test_stat, pvalue = proportions_ztest(count=[df.loc[df["NEW_IS_ALONE"] == "YES", "Survived"].sum(),
                                            df.loc[df["NEW_IS_ALONE"] == "NO", "Survived"].sum()],
                                      
                                      nobs=[df.loc[df["NEW_IS_ALONE"] == "YES", "Survived"].shape[0],
                                           df.loc[df["NEW_IS_ALONE"] == "NO", "Survived"].shape[0]])

print('Test Stat = %.4f, p-value = %.4f' % (test_stat, pvalue))

Test Stat = -6.0704, p-value = 0.0000

evet fark var gibi gözüküyor h0 hipotezi reddedilir. h0 hipotezi der ki iki oran arasında farkı yoktur, tamam reddedildi varmış. bu durum mutlak olarak hayatta kalma durumunu etkilediğini göstermez ancak göz ardı edilemeyeceğini gösterir. bunun etkisini daha net şekilde modelleme bölümünde göreceğiz.

# TEXT FEATURES

metinler üzerinden özellikler türetmeye çalışacağız.

In [12]:
df = load()
df.head()

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S

In [13]:
# örneğin name değişkenindeki metinlerden değişken türetmeye çalışacağım. bruada 
#fazlaca metin var normalde kardinalitesi yüksek benim içim çöp olan bir değişkendi ancak içerisinden 
#featurelar türetilebilir.


#örneğin harf saydırma, buradaki isimleri saydırarak kaç harf oldukalrını bulabiliriz.
#burada dikkat yorum yapıyorum, çok önemli olmak zorunda değil. incelemeye çalışıyorum emta bilgi geldi aklıma vs.
#örn kraliyet ailesinden biri vrdır belki. sadece deniyorum. yaratıcı olmam gerekiyor

In [14]:
df["NEW_NAME_COUNT"] = df["Name"].str.len()
df
#burada bir değişkendeki harf sayısı ne kadardır bu şekilde hesaplamış olurum.

     PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch              Ticket    Fare            Cabin Embarked  NEW_NAME_COUNT
0              1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0           A/5 21171   7.250              NaN        S              23
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0            PC 17599  71.283              C85        C              51
2              3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0    STON/O2. 3101282   7.925              NaN        S              22
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0              113803  53.100             C123        S              44
4              5         0       3                           Allen, Mr. William Henry    male 35.000      0      0              373450   8.050              NaN        S              24
5              6         0       3                                   Moran, Mr. James    male    NaN      0      0              330877   8.458              NaN        Q              16
6              7         0       1                            McCarthy, Mr. Timothy J    male 54.000      0      0               17463  51.862              E46        S              23
7              8         0       3                     Palsson, Master. Gosta Leonard    male  2.000      3      1              349909  21.075              NaN        S              30
8              9         1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female 27.000      0      2              347742  11.133              NaN        S              49
9             10         1       2                Nasser, Mrs. Nicholas (Adele Achem)  female 14.000      1      0              237736  30.071              NaN        C              35
10            11         1       3                    Sandstrom, Miss. Marguerite Rut  female  4.000      1      1             PP 9549  16.700               G6        S              31
11            12         1       1                           Bonnell, Miss. Elizabeth  female 58.000      0      0              113783  26.550             C103        S              24
12            13         0       3                     Saundercock, Mr. William Henry    male 20.000      0      0           A/5. 2151   8.050              NaN        S              30
13            14         0       3                        Andersson, Mr. Anders Johan    male 39.000      1      5              347082  31.275              NaN        S              27
14            15         0       3               Vestrom, Miss. Hulda Amanda Adolfina  female 14.000      0      0              350406   7.854              NaN        S              36
15            16         1       2                   Hewlett, Mrs. (Mary D Kingcome)   female 55.000      0      0              248706  16.000              NaN        S              32
16            17         0       3                               Rice, Master. Eugene    male  2.000      4      1              382652  29.125              NaN        Q              20
17            18         1       2                       Williams, Mr. Charles Eugene    male    NaN      0      0              244373  13.000              NaN        S              28
18            19         0       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female 31.000      1      0              345763  18.000              NaN        S              55
19            20         1       3                            Masselmani, Mrs. Fatima  female    NaN      0      0                2649   7.225              NaN        C              23
20            21         0       2                               Fynney, Mr. Joseph J    male 35.000      0      0              239865  26.000              NaN        S              20
21            22         1       2                              Beesley, Mr. Lawrence    male 34.000      0      0              248698  13.000              D56        S              21
22            23         1       3                        McGowan, Miss. Anna "Annie"  female 15.000      0      0              330923   8.029              NaN        Q              27
23            24         1       1                       Sloper, Mr. William Thompson    male 28.000      0      0              113788  35.500               A6        S              28
24            25         0       3                      Palsson, Miss. Torborg Danira  female  8.000      3      1              349909  21.075              NaN        S              29
25            26         1       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female 38.000      1      5              347077  31.387              NaN        S              57
26            27         0       3                            Emir, Mr. Farred Chehab    male    NaN      0      0                2631   7.225              NaN        C              23
27            28         0       1                     Fortune, Mr. Charles Alexander    male 19.000      3      2               19950 263.000      C23 C25 C27        S              30
28            29         1       3                      O'Dwyer, Miss. Ellen "Nellie"  female    NaN      0      0              330959   7.879              NaN        Q              29
29            30         0       3                                Todoroff, Mr. Lalio    male    NaN      0      0              349216   7.896              NaN        S              19
30            31         0       1                           Uruchurtu, Don. Manuel E    male 40.000      0      0            PC 17601  27.721              NaN        C              24
31            32         1       1     Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1      0            PC 17569 146.521              B78        C              46
32            33         1       3                           Glynn, Miss. Mary Agatha  female    NaN      0      0              335677   7.750              NaN        Q              24
33            34         0       2                              Wheadon, Mr. Edward H    male 66.000      0      0          C.A. 24579  10.500              NaN        S              21
34            35         0       1                            Meyer, Mr. Edgar Joseph    male 28.000      1      0            PC 17604  82.171              NaN        C              23
35            36         0       1                     Holverson, Mr. Alexander Oskar    male 42.000      1      0              113789  52.000              NaN        S              30
36            37         1       3                                   Mamee, Mr. Hanna    male    NaN      0      0                2677   7.229              NaN        C              16
37            38         0       3                           Cann, Mr. Ernest Charles    male 21.000      0      0          A./5. 2152   8.050              NaN        S              24
38            39         0       3                 Vander Planke, Miss. Augusta Maria  female 18.000      2      0              345764  18.000              NaN        S              34
39            40         1       3                        Nicola-Yarred, Miss. Jamila  female 14.000      1      0                2651  11.242              NaN        C              27
40            41         0       3     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female 40.000      1      0                7546   9.475              NaN        S              46
41            42         0       2  Turpin, Mrs. William John Robert (Dorothy Ann ...  female 27.000      1      0               11668  21.000              NaN        S              56
42            43         0       3                                Kraeff, Mr. Theodor    male    NaN      0      0              349253   7.896              NaN        C              19
43            44         1       2           Laroche, Miss. Simonne Marie Anne Andree  female  3.000      1      2       SC/Paris 2123  41.579              NaN        C              40
44            45         1       3                      Devaney, Miss. Margaret Delia  female 19.000      0      0              330958   7.879              NaN        Q              29
45            46         0       3                           Rogers, Mr. William John    male    NaN      0      0     S.C./A.4. 23567   8.050              NaN        S              24
46            47         0       3                                  Lennon, Mr. Denis    male    NaN      1      0              370371  15.500              NaN        Q              17
47            48         1       3                          O'Driscoll, Miss. Bridget  female    NaN      0      0               14311   7.750              NaN        Q              25
48            49         0       3                                Samaan, Mr. Youssef    male    NaN      2      0                2662  21.679              NaN        C              19
49            50         0       3      Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female 18.000      1      0              349237  17.800              NaN        S              45
50            51         0       3                         Panula, Master. Juha Niilo    male  7.000      4      1             3101295  39.688              NaN        S              26
51            52         0       3                       Nosworthy, Mr. Richard Cater    male 21.000      0      0          A/4. 39886   7.800              NaN        S              28
52            53         1       1           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female 49.000      1      0            PC 17572  76.729              D33        C              40
53            54         1       2  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female 29.000      1      0                2926  26.000              NaN        S              50
54            55         0       1                     Ostby, Mr. Engelhart Cornelius    male 65.000      0      1              113509  61.979              B30        C              30
55            56         1       1                                  Woolner, Mr. Hugh    male    NaN      0      0               19947  35.500              C52        S              17
56            57         1       2                                  Rugg, Miss. Emily  female 21.000      0      0          C.A. 31026  10.500              NaN        S              17
57            58         0       3                                Novel, Mr. Mansouer    male 28.500      0      0                2697   7.229              NaN        C              19
58            59         1       2                       West, Miss. Constance Mirium  female  5.000      1      2          C.A. 34651  27.750              NaN        S              28
59            60         0       3                 Goodwin, Master. William Frederick    male 11.000      5      2             CA 2144  46.900              NaN        S              34
60            61         0       3                              Sirayanian, Mr. Orsen    male 22.000      0      0                2669   7.229              NaN        C              21
61            62         1       1                                Icard, Miss. Amelie  female 38.000      0      0              113572  80.000              B28      NaN              19
62            63         0       1                        Harris, Mr. Henry Birkhardt    male 45.000      1      0               36973  83.475              C83        S              27
63            64         0       3                              Skoog, Master. Harald    male  4.000      3      2              347088  27.900              NaN        S              21
64            65         0       1                              Stewart, Mr. Albert A    male    NaN      0      0            PC 17605  27.721              NaN        C              21
65            66         1       3                           Moubarek, Master. Gerios    male    NaN      1      1                2661  15.246              NaN        C              24
66            67         1       2                       Nye, Mrs. (Elizabeth Ramell)  female 29.000      0      0          C.A. 29395  10.500              F33        S              28
67            68         0       3                           Crease, Mr. Ernest James    male 19.000      0      0           S.P. 3464   8.158              NaN        S              24
68            69         1       3                    Andersson, Miss. Erna Alexandra  female 17.000      4      2             3101281   7.925              NaN        S              31
69            70         0       3                                  Kink, Mr. Vincenz    male 26.000      2      0              315151   8.662              NaN        S              17
70            71         0       2                         Jenkin, Mr. Stephen Curnow    male 32.000      0      0          C.A. 33111  10.500              NaN        S              26
71            72         0       3                         Goodwin, Miss. Lillian Amy  female 16.000      5      2             CA 2144  46.900              NaN        S              26
72            73         0       2                               Hood, Mr. Ambrose Jr    male 21.000      0      0        S.O.C. 14879  73.500              NaN        S              20
73            74         0       3                        Chronopoulos, Mr. Apostolos    male 26.000      1      0                2680  14.454              NaN        C              27
74            75         1       3                                      Bing, Mr. Lee    male 32.000      0      0                1601  56.496              NaN        S              13
75            76         0       3                            Moen, Mr. Sigurd Hansen    male 25.000      0      0              348123   7.650            F G73        S              23
76            77         0       3                                  Staneff, Mr. Ivan    male    NaN      0      0              349208   7.896              NaN        S              17
77            78         0       3                           Moutal, Mr. Rahamin Haim    male    NaN      0      0              374746   8.050              NaN        S              24
78            79         1       2                      Caldwell, Master. Alden Gates    male  0.830      0      2              248738  29.000              NaN        S              29
79            80         1       3                           Dowdell, Miss. Elizabeth  female 30.000      0      0              364516  12.475              NaN        S              24
80            81         0       3                               Waelens, Mr. Achille    male 22.000      0      0              345767   9.000              NaN        S              20
81            82         1       3                        Sheerlinck, Mr. Jan Baptist    male 29.000      0      0              345779   9.500              NaN        S              27
82            83         1       3                     McDermott, Miss. Brigdet Delia  female    NaN      0      0              330932   7.787              NaN        Q              30
83            84         0       1                            Carrau, Mr. Francisco M    male 28.000      0      0              113059  47.100              NaN        S              23
84            85         1       2                                Ilett, Miss. Bertha  female 17.000      0      0          SO/C 14885  10.500              NaN        S              19
85            86         1       3  Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  female 33.000      3      0             3101278  15.850              NaN        S              55
86            87         0       3                             Ford, Mr. William Neal    male 16.000      1      3          W./C. 6608  34.375              NaN        S              22
87            88         0       3                      Slocovski, Mr. Selman Francis    male    NaN      0      0     SOTON/OQ 392086   8.050              NaN        S              29
88            89         1       1                         Fortune, Miss. Mabel Helen  female 23.000      3      2               19950 263.000      C23 C25 C27        S              26
89            90         0       3                             Celotti, Mr. Francesco    male 24.000      0      0              343275   8.050              NaN        S              22
90            91         0       3                               Christmann, Mr. Emil    male 29.000      0      0              343276   8.050              NaN        S              20
91            92         0       3                         Andreasson, Mr. Paul Edvin    male 20.000      0      0              347466   7.854              NaN        S              26
92            93         0       1                        Chaffee, Mr. Herbert Fuller    male 46.000      1      0         W.E.P. 5734  61.175              E31        S              27
93            94         0       3                            Dean, Mr. Bertram Frank    male 26.000      1      2           C.A. 2315  20.575              NaN        S              23
94            95         0       3                                  Coxon, Mr. Daniel    male 59.000      0      0              364500   7.250              NaN        S              17
95            96         0       3                        Shorney, Mr. Charles Joseph    male    NaN      0      0              374910   8.050              NaN        S              27
96            97         0       1                          Goldschmidt, Mr. George B    male 71.000      0      0            PC 17754  34.654               A5        C              25
97            98         1       1                    Greenfield, Mr. William Bertram    male 23.000      0      1            PC 17759  63.358          D10 D12        C              31
98            99         1       2               Doling, Mrs. John T (Ada Julia Bone)  female 34.000      0      1              231919  23.000              NaN        S              36
99           100         0       2                                  Kantor, Mr. Sinai    male 34.000      1      0              244367  26.000              NaN        S              17
100          101         0       3                            Petranec, Miss. Matilda  female 28.000      0      0              349245   7.896              NaN        S              23
101          102         0       3                   Petroff, Mr. Pastcho ("Pentcho")    male    NaN      0      0              349215   7.896              NaN        S              32
102          103         0       1                          White, Mr. Richard Frasar    male 21.000      0      1               35281  77.287              D26        S              25
103          104         0       3                         Johansson, Mr. Gustaf Joel    male 33.000      0      0                7540   8.654              NaN        S              26
104          105         0       3                     Gustafsson, Mr. Anders Vilhelm    male 37.000      2      0             3101276   7.925              NaN        S              30
105          106         0       3                              Mionoff, Mr. Stoytcho    male 28.000      0      0              349207   7.896              NaN        S              21
106          107         1       3                   Salkjelsvik, Miss. Anna Kristine  female 21.000      0      0              343120   7.650              NaN        S              32

In [15]:
#harfleri saydıktan sonra kelimeleri de sayabilirim 
#word count

df["NEW_NAME_WORD_COUNT"] = df["Name"].apply(lambda x: len(str(x).split(" ")))
# lambda ilgili ismi yakaladığında str'ye çevirsin daha sonra boşluklara göre split etsin
#splitten sonra kaç kelime varsa bunları say ve bunu yeni değişkene ata.
df

     PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch              Ticket    Fare            Cabin Embarked  NEW_NAME_COUNT  NEW_NAME_WORD_COUNT
0              1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0           A/5 21171   7.250              NaN        S              23                    4
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0            PC 17599  71.283              C85        C              51                    7
2              3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0    STON/O2. 3101282   7.925              NaN        S              22                    3
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0              113803  53.100             C123        S              44                    7
4              5         0       3                           Allen, Mr. William Henry    male 35.000      0      0              373450   8.050              NaN        S              24                    4
5              6         0       3                                   Moran, Mr. James    male    NaN      0      0              330877   8.458              NaN        Q              16                    3
6              7         0       1                            McCarthy, Mr. Timothy J    male 54.000      0      0               17463  51.862              E46        S              23                    4
7              8         0       3                     Palsson, Master. Gosta Leonard    male  2.000      3      1              349909  21.075              NaN        S              30                    4
8              9         1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female 27.000      0      2              347742  11.133              NaN        S              49                    7
9             10         1       2                Nasser, Mrs. Nicholas (Adele Achem)  female 14.000      1      0              237736  30.071              NaN        C              35                    5
10            11         1       3                    Sandstrom, Miss. Marguerite Rut  female  4.000      1      1             PP 9549  16.700               G6        S              31                    4
11            12         1       1                           Bonnell, Miss. Elizabeth  female 58.000      0      0              113783  26.550             C103        S              24                    3
12            13         0       3                     Saundercock, Mr. William Henry    male 20.000      0      0           A/5. 2151   8.050              NaN        S              30                    4
13            14         0       3                        Andersson, Mr. Anders Johan    male 39.000      1      5              347082  31.275              NaN        S              27                    4
14            15         0       3               Vestrom, Miss. Hulda Amanda Adolfina  female 14.000      0      0              350406   7.854              NaN        S              36                    5
15            16         1       2                   Hewlett, Mrs. (Mary D Kingcome)   female 55.000      0      0              248706  16.000              NaN        S              32                    6
16            17         0       3                               Rice, Master. Eugene    male  2.000      4      1              382652  29.125              NaN        Q              20                    3
17            18         1       2                       Williams, Mr. Charles Eugene    male    NaN      0      0              244373  13.000              NaN        S              28                    4
18            19         0       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female 31.000      1      0              345763  18.000              NaN        S              55                    7
19            20         1       3                            Masselmani, Mrs. Fatima  female    NaN      0      0                2649   7.225              NaN        C              23                    3
20            21         0       2                               Fynney, Mr. Joseph J    male 35.000      0      0              239865  26.000              NaN        S              20                    4
21            22         1       2                              Beesley, Mr. Lawrence    male 34.000      0      0              248698  13.000              D56        S              21                    3
22            23         1       3                        McGowan, Miss. Anna "Annie"  female 15.000      0      0              330923   8.029              NaN        Q              27                    4
23            24         1       1                       Sloper, Mr. William Thompson    male 28.000      0      0              113788  35.500               A6        S              28                    4
24            25         0       3                      Palsson, Miss. Torborg Danira  female  8.000      3      1              349909  21.075              NaN        S              29                    4
25            26         1       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female 38.000      1      5              347077  31.387              NaN        S              57                    8
26            27         0       3                            Emir, Mr. Farred Chehab    male    NaN      0      0                2631   7.225              NaN        C              23                    4
27            28         0       1                     Fortune, Mr. Charles Alexander    male 19.000      3      2               19950 263.000      C23 C25 C27        S              30                    4
28            29         1       3                      O'Dwyer, Miss. Ellen "Nellie"  female    NaN      0      0              330959   7.879              NaN        Q              29                    4
29            30         0       3                                Todoroff, Mr. Lalio    male    NaN      0      0              349216   7.896              NaN        S              19                    3
30            31         0       1                           Uruchurtu, Don. Manuel E    male 40.000      0      0            PC 17601  27.721              NaN        C              24                    4
31            32         1       1     Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1      0            PC 17569 146.521              B78        C              46                    6
32            33         1       3                           Glynn, Miss. Mary Agatha  female    NaN      0      0              335677   7.750              NaN        Q              24                    4
33            34         0       2                              Wheadon, Mr. Edward H    male 66.000      0      0          C.A. 24579  10.500              NaN        S              21                    4
34            35         0       1                            Meyer, Mr. Edgar Joseph    male 28.000      1      0            PC 17604  82.171              NaN        C              23                    4
35            36         0       1                     Holverson, Mr. Alexander Oskar    male 42.000      1      0              113789  52.000              NaN        S              30                    4
36            37         1       3                                   Mamee, Mr. Hanna    male    NaN      0      0                2677   7.229              NaN        C              16                    3
37            38         0       3                           Cann, Mr. Ernest Charles    male 21.000      0      0          A./5. 2152   8.050              NaN        S              24                    4
38            39         0       3                 Vander Planke, Miss. Augusta Maria  female 18.000      2      0              345764  18.000              NaN        S              34                    5
39            40         1       3                        Nicola-Yarred, Miss. Jamila  female 14.000      1      0                2651  11.242              NaN        C              27                    3
40            41         0       3     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female 40.000      1      0                7546   9.475              NaN        S              46                    6
41            42         0       2  Turpin, Mrs. William John Robert (Dorothy Ann ...  female 27.000      1      0               11668  21.000              NaN        S              56                    8
42            43         0       3                                Kraeff, Mr. Theodor    male    NaN      0      0              349253   7.896              NaN        C              19                    3
43            44         1       2           Laroche, Miss. Simonne Marie Anne Andree  female  3.000      1      2       SC/Paris 2123  41.579              NaN        C              40                    6
44            45         1       3                      Devaney, Miss. Margaret Delia  female 19.000      0      0              330958   7.879              NaN        Q              29                    4
45            46         0       3                           Rogers, Mr. William John    male    NaN      0      0     S.C./A.4. 23567   8.050              NaN        S              24                    4
46            47         0       3                                  Lennon, Mr. Denis    male    NaN      1      0              370371  15.500              NaN        Q              17                    3
47            48         1       3                          O'Driscoll, Miss. Bridget  female    NaN      0      0               14311   7.750              NaN        Q              25                    3
48            49         0       3                                Samaan, Mr. Youssef    male    NaN      2      0                2662  21.679              NaN        C              19                    3
49            50         0       3      Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female 18.000      1      0              349237  17.800              NaN        S              45                    5
50            51         0       3                         Panula, Master. Juha Niilo    male  7.000      4      1             3101295  39.688              NaN        S              26                    4
51            52         0       3                       Nosworthy, Mr. Richard Cater    male 21.000      0      0          A/4. 39886   7.800              NaN        S              28                    4
52            53         1       1           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female 49.000      1      0            PC 17572  76.729              D33        C              40                    6
53            54         1       2  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female 29.000      1      0                2926  26.000              NaN        S              50                    6
54            55         0       1                     Ostby, Mr. Engelhart Cornelius    male 65.000      0      1              113509  61.979              B30        C              30                    4
55            56         1       1                                  Woolner, Mr. Hugh    male    NaN      0      0               19947  35.500              C52        S              17                    3
56            57         1       2                                  Rugg, Miss. Emily  female 21.000      0      0          C.A. 31026  10.500              NaN        S              17                    3
57            58         0       3                                Novel, Mr. Mansouer    male 28.500      0      0                2697   7.229              NaN        C              19                    3
58            59         1       2                       West, Miss. Constance Mirium  female  5.000      1      2          C.A. 34651  27.750              NaN        S              28                    4
59            60         0       3                 Goodwin, Master. William Frederick    male 11.000      5      2             CA 2144  46.900              NaN        S              34                    4
60            61         0       3                              Sirayanian, Mr. Orsen    male 22.000      0      0                2669   7.229              NaN        C              21                    3
61            62         1       1                                Icard, Miss. Amelie  female 38.000      0      0              113572  80.000              B28      NaN              19                    3
62            63         0       1                        Harris, Mr. Henry Birkhardt    male 45.000      1      0               36973  83.475              C83        S              27                    4
63            64         0       3                              Skoog, Master. Harald    male  4.000      3      2              347088  27.900              NaN        S              21                    3
64            65         0       1                              Stewart, Mr. Albert A    male    NaN      0      0            PC 17605  27.721              NaN        C              21                    4
65            66         1       3                           Moubarek, Master. Gerios    male    NaN      1      1                2661  15.246              NaN        C              24                    3
66            67         1       2                       Nye, Mrs. (Elizabeth Ramell)  female 29.000      0      0          C.A. 29395  10.500              F33        S              28                    4
67            68         0       3                           Crease, Mr. Ernest James    male 19.000      0      0           S.P. 3464   8.158              NaN        S              24                    4
68            69         1       3                    Andersson, Miss. Erna Alexandra  female 17.000      4      2             3101281   7.925              NaN        S              31                    4
69            70         0       3                                  Kink, Mr. Vincenz    male 26.000      2      0              315151   8.662              NaN        S              17                    3
70            71         0       2                         Jenkin, Mr. Stephen Curnow    male 32.000      0      0          C.A. 33111  10.500              NaN        S              26                    4
71            72         0       3                         Goodwin, Miss. Lillian Amy  female 16.000      5      2             CA 2144  46.900              NaN        S              26                    4
72            73         0       2                               Hood, Mr. Ambrose Jr    male 21.000      0      0        S.O.C. 14879  73.500              NaN        S              20                    4
73            74         0       3                        Chronopoulos, Mr. Apostolos    male 26.000      1      0                2680  14.454              NaN        C              27                    3
74            75         1       3                                      Bing, Mr. Lee    male 32.000      0      0                1601  56.496              NaN        S              13                    3
75            76         0       3                            Moen, Mr. Sigurd Hansen    male 25.000      0      0              348123   7.650            F G73        S              23                    4
76            77         0       3                                  Staneff, Mr. Ivan    male    NaN      0      0              349208   7.896              NaN        S              17                    3
77            78         0       3                           Moutal, Mr. Rahamin Haim    male    NaN      0      0              374746   8.050              NaN        S              24                    4
78            79         1       2                      Caldwell, Master. Alden Gates    male  0.830      0      2              248738  29.000              NaN        S              29                    4
79            80         1       3                           Dowdell, Miss. Elizabeth  female 30.000      0      0              364516  12.475              NaN        S              24                    3
80            81         0       3                               Waelens, Mr. Achille    male 22.000      0      0              345767   9.000              NaN        S              20                    3
81            82         1       3                        Sheerlinck, Mr. Jan Baptist    male 29.000      0      0              345779   9.500              NaN        S              27                    4
82            83         1       3                     McDermott, Miss. Brigdet Delia  female    NaN      0      0              330932   7.787              NaN        Q              30                    4
83            84         0       1                            Carrau, Mr. Francisco M    male 28.000      0      0              113059  47.100              NaN        S              23                    4
84            85         1       2                                Ilett, Miss. Bertha  female 17.000      0      0          SO/C 14885  10.500              NaN        S              19                    3
85            86         1       3  Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  female 33.000      3      0             3101278  15.850              NaN        S              55                    7
86            87         0       3                             Ford, Mr. William Neal    male 16.000      1      3          W./C. 6608  34.375              NaN        S              22                    4
87            88         0       3                      Slocovski, Mr. Selman Francis    male    NaN      0      0     SOTON/OQ 392086   8.050              NaN        S              29                    4
88            89         1       1                         Fortune, Miss. Mabel Helen  female 23.000      3      2               19950 263.000      C23 C25 C27        S              26                    4
89            90         0       3                             Celotti, Mr. Francesco    male 24.000      0      0              343275   8.050              NaN        S              22                    3
90            91         0       3                               Christmann, Mr. Emil    male 29.000      0      0              343276   8.050              NaN        S              20                    3
91            92         0       3                         Andreasson, Mr. Paul Edvin    male 20.000      0      0              347466   7.854              NaN        S              26                    4
92            93         0       1                        Chaffee, Mr. Herbert Fuller    male 46.000      1      0         W.E.P. 5734  61.175              E31        S              27                    4
93            94         0       3                            Dean, Mr. Bertram Frank    male 26.000      1      2           C.A. 2315  20.575              NaN        S              23                    4
94            95         0       3                                  Coxon, Mr. Daniel    male 59.000      0      0              364500   7.250              NaN        S              17                    3
95            96         0       3                        Shorney, Mr. Charles Joseph    male    NaN      0      0              374910   8.050              NaN        S              27                    4

In [16]:
#bu textlerin içerisindeki özel yapıları yakalamaya çalışalım.
# teori bölümünde görmüştük ki bu texlerin içerisinde dr ifadeleri vs vardı bunları yakalamaya çalışacağım.
# örn dr ifadesine sahip olanları flaglesek, benim elimde gemidekilerin meslekleri hakkında bilgi yok ancak
# burada önemli bir bakış açısıyla featurelarımı türeterek değerlendireceğim, modelleme konusunda değerlendiririm diyorum
# ancak burada asıl yapmak istediğim şey olabildiğince az sayıda değişkenle yüksek başarılara erişmektir bunu da unutmamak lazım.
# o yüzden rare encodingte elemeler yaptık. ancak feature eng bölümünde öyle featurelar türeyebilir ki
# hataları düşürebilir, model başarımı yükseltebilir. o yüzden olabildiğince kurcalıyorum.

df["NEW_NAME_DR"] = df["Name"].apply(lambda x: len([x for x in x.split() if x.startswith("Dr")]))
#ilk olarak bu name sütununu split et sonra buradaki her bir kelime liste olarak erişebiliyor olacak
#splitten sonra for ile bu listeleri gez, eğer her listenin başı startswith ile başlıyorsa bunu seç diyorum.
df.head()

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked  NEW_NAME_COUNT  NEW_NAME_WORD_COUNT  NEW_NAME_DR
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S              23                    4            0
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C              51                    7            0
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S              22                    3            0
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S              44                    7            0
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S              24                    4            0

In [17]:
#burada göremiyorum tabi, şimdi bunu drye göre groupbya alıp surviveda göre ortalamsını alacağım

df.groupby("NEW_NAME_DR").agg({"Survived": "mean"})
#burada surviveda göre ortalamasını aldıktan sonra dr olanların hayatta kalma oranı daha yüksektir.

             Survived
NEW_NAME_DR
0               0.383
1               0.500

In [18]:
#kategorik değişken olduğu için frekanslarını gözlemliyoruz.
df.groupby("NEW_NAME_DR").agg({"Survived": ["mean", "count"]})#countunu gözlemliyorum
#900 gözlemin oldupu yerde 1 0tane doktor olması ne kadar önemli tartışmalı olduğu için dursun bi bakalım diyorum.

            Survived
                mean count
NEW_NAME_DR
0              0.383   881
1              0.500    10

# REGEX FEATURES

In [19]:
#regex ile değişken türeteceğiz.
df.head()

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked  NEW_NAME_COUNT  NEW_NAME_WORD_COUNT  NEW_NAME_DR
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S              23                    4            0
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C              51                    7            0
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S              22                    3            0
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S              44                    7            0
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S              24                    4            0

In [20]:
#buradaki titlelar bizim için önemli olabilir name kolonunu kontrol edeceğim.
#burada nasıl bir yol izlemem gerektiğini düşünüyorum. burada bir pattern, örüntü yakalamaya çalışıyorum
#burada regex ile bir feature üretmek istediğimde bir örüntü yakalamam gerekiyor. örn Mrs. için öncesinde ve sonrasında 
#boşluk olup büyük harfle başlayacak ve sonunda nokta olacak. bu diğer titlelar için de geçerli

df["NEW_TITLE"] = df.Name.str.extract(' ([A-Za-z]+)\.', expand=False)
# extract çıkar diyorum, nasıl çıkaracağım, başında boşluk olsun büyük harfle başlayacak
# sonunda nokta olacak, büyük ya da küçük harflerden oluşacak şekilde göreceğin bu harfleri yakala
# her senaryoya göre özel olarak ayarlanması gerekmektedir.
df.head()

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked  NEW_NAME_COUNT  NEW_NAME_WORD_COUNT  NEW_NAME_DR NEW_TITLE
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S              23                    4            0        Mr
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C              51                    7            0       Mrs
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S              22                    3            0      Miss
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S              44                    7            0       Mrs
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S              24                    4            0        Mr

In [22]:
df[["NEW_TITLE", "Survived","Age"]].groupby(["NEW_TITLE"]).agg({"Survived":"mean", "Age": ["count","mean"]})
# new titleı seç, survivedı seç, agei seç new_titlea göre groupbya al, sonra survivedın ortalamasını al yaş değişkeninin
# countunu ve ortalamsını al

          Survived   Age
              mean count   mean
NEW_TITLE
Capt         0.000     1 70.000
Col          0.500     2 58.000
Countess     1.000     1 33.000
Don          0.000     1 40.000
Dr           0.429     6 42.000
Jonkheer     0.000     1 38.000
Lady         1.000     1 48.000
Major        0.500     2 48.500
Master       0.575    36  4.574
Miss         0.698   146 21.774
Mlle         1.000     2 24.000
Mme          1.000     1 24.000
Mr           0.157   398 32.368
Mrs          0.792   108 35.898
Ms           1.000     1 28.000
Rev          0.000     6 43.167
Sir          1.000     1 49.000

bizim için gözlenme ihtimali olmayan değişkenden bile çok değerli bir bilgi çıkardık. titlelarımı çıkardım örn kaptan varmış. drda bulunan frekas farklılığını sonra araştıracağız. buradan çıkardığım bilgiye göre ortık örn yaş değişkeninde tamamen hepsine ortalama ile doldurmamam gerektiğini anladım, neden? titlelara göre yaş ortalamaları zaten farklı çıkıyor. frekasnları yüksek olan titleların yaş ortalaması kayda değer bilgi içeriyor. örn artık yaş değişkenimdeki boşlukları titleların ortalamasına göre doldurmam daha mantıklı. değişken üretmenin olası senaryolarda ne kadar faydalı olabileceğini göstermiş olduk, analiz yaptık.

# DATE FEATURES

bu bölümde date featureları üretiyor olacağız.

In [23]:
dff = pd.read_csv("course_reviews.csv")
dff.head()

   Rating            Timestamp             Enrolled  Progress  Questions Asked  Questions Answered
0   5.000  2021-02-05 07:45:55  2021-01-25 15:12:08     5.000            0.000               0.000
1   5.000  2021-02-04 21:05:32  2021-02-04 20:43:40     1.000            0.000               0.000
2   4.500  2021-02-04 20:34:03  2019-07-04 23:23:27     1.000            0.000               0.000
3   5.000  2021-02-04 16:56:28  2021-02-04 14:41:29    10.000            0.000               0.000
4   4.000  2021-02-04 15:00:24  2020-10-13 03:10:07    10.000            0.000               0.000

In [24]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4323 entries, 0 to 4322
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rating              4323 non-null   float64
 1   Timestamp           4323 non-null   object
 2   Enrolled            4323 non-null   object
 3   Progress            4323 non-null   float64
 4   Questions Asked     4323 non-null   float64
 5   Questions Answered  4323 non-null   float64
dtypes: float64(4), object(2)
memory usage: 202.8+ KB

kursa yapılan puanlamalar , puanlama tarihi , kursa üye olma tarihi ilerleme durumu, sorduğu sorular, yanıtlanan sorular gibi değişkenler var, amacım timestamp değişkeninden yeni değişkenler türetmek.

ancak bir problemim var tarih değişkeni olması gereken değişken object tipinde

In [25]:
dff["Timestamp"] = pd.to_datetime(dff["Timestamp"], format = "%Y-%m-%d")
# to_datetime metodu dönüştürmek istediğimiz sütuunu ister ve formatını girmemizi bekler

In [27]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4323 entries, 0 to 4322
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rating              4323 non-null   float64
 1   Timestamp           4323 non-null   datetime64[ns]
 2   Enrolled            4323 non-null   object
 3   Progress            4323 non-null   float64
 4   Questions Asked     4323 non-null   float64
 5   Questions Answered  4323 non-null   float64
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 202.8+ KB

In [32]:
# örneğin buradan bir yıl değişkeni türetmeye çalışıyorum

dff["year"] = dff["Timestamp"].dt.year #dt datetime modelünü kullanarak yılı çek diyorum
dff.head()

   Rating           Timestamp             Enrolled  Progress  Questions Asked  Questions Answered  year  month
0   5.000 2021-02-05 07:45:55  2021-01-25 15:12:08     5.000            0.000               0.000  2021      2
1   5.000 2021-02-04 21:05:32  2021-02-04 20:43:40     1.000            0.000               0.000  2021      2
2   4.500 2021-02-04 20:34:03  2019-07-04 23:23:27     1.000            0.000               0.000  2021      2
3   5.000 2021-02-04 16:56:28  2021-02-04 14:41:29    10.000            0.000               0.000  2021      2
4   4.000 2021-02-04 15:00:24  2020-10-13 03:10:07    10.000            0.000               0.000  2021      2

In [33]:
dff["month"] = dff["Timestamp"].dt.month # aynı işlem ay için
dff.head()

   Rating           Timestamp             Enrolled  Progress  Questions Asked  Questions Answered  year  month
0   5.000 2021-02-05 07:45:55  2021-01-25 15:12:08     5.000            0.000               0.000  2021      2
1   5.000 2021-02-04 21:05:32  2021-02-04 20:43:40     1.000            0.000               0.000  2021      2
2   4.500 2021-02-04 20:34:03  2019-07-04 23:23:27     1.000            0.000               0.000  2021      2
3   5.000 2021-02-04 16:56:28  2021-02-04 14:41:29    10.000            0.000               0.000  2021      2
4   4.000 2021-02-04 15:00:24  2020-10-13 03:10:07    10.000            0.000               0.000  2021      2

In [34]:
dff['year_diff'] = date.today().year - dff["Timestamp"].dt.year
dff.head() #yılların farkını geetirebilirim bu yıldan

   Rating           Timestamp             Enrolled  Progress  Questions Asked  Questions Answered  year  month  year_diff
0   5.000 2021-02-05 07:45:55  2021-01-25 15:12:08     5.000            0.000               0.000  2021      2          3
1   5.000 2021-02-04 21:05:32  2021-02-04 20:43:40     1.000            0.000               0.000  2021      2          3
2   4.500 2021-02-04 20:34:03  2019-07-04 23:23:27     1.000            0.000               0.000  2021      2          3
3   5.000 2021-02-04 16:56:28  2021-02-04 14:41:29    10.000            0.000               0.000  2021      2          3
4   4.000 2021-02-04 15:00:24  2020-10-13 03:10:07    10.000            0.000               0.000  2021      2          3

In [35]:
# iki tarih arasındaki ay farkı: yıl farkı + ay farkı

dff["month_diff"] = (date.today().year - dff["Timestamp"].dt.year) * 12 + date.today().month - dff["Timestamp"].dt.month
# iki tarih arasındaki ay farkını hesaplamak içinn bunu önce yıl olarak hesaplayıp sonra bunu ay şeklindeçevirmemiz lazım
# sonra bunların ay farkını alıyorum
dff.head()

   Rating           Timestamp             Enrolled  Progress  Questions Asked  Questions Answered  year  month  year_diff  month_diff
0   5.000 2021-02-05 07:45:55  2021-01-25 15:12:08     5.000            0.000               0.000  2021      2          3          42
1   5.000 2021-02-04 21:05:32  2021-02-04 20:43:40     1.000            0.000               0.000  2021      2          3          42
2   4.500 2021-02-04 20:34:03  2019-07-04 23:23:27     1.000            0.000               0.000  2021      2          3          42
3   5.000 2021-02-04 16:56:28  2021-02-04 14:41:29    10.000            0.000               0.000  2021      2          3          42
4   4.000 2021-02-04 15:00:24  2020-10-13 03:10:07    10.000            0.000               0.000  2021      2          3          42

In [36]:
# günlerin isim bilgilerine erişmek istersem

dff["day_name"] = dff["Timestamp"].dt.day_name()
dff.head() # day name metodunu kullanarak bu bilgiye ulaşa bilirim

   Rating           Timestamp             Enrolled  Progress  Questions Asked  Questions Answered  year  month  year_diff  month_diff  day_name
0   5.000 2021-02-05 07:45:55  2021-01-25 15:12:08     5.000            0.000               0.000  2021      2          3          42    Friday
1   5.000 2021-02-04 21:05:32  2021-02-04 20:43:40     1.000            0.000               0.000  2021      2          3          42  Thursday
2   4.500 2021-02-04 20:34:03  2019-07-04 23:23:27     1.000            0.000               0.000  2021      2          3          42  Thursday
3   5.000 2021-02-04 16:56:28  2021-02-04 14:41:29    10.000            0.000               0.000  2021      2          3          42  Thursday
4   4.000 2021-02-04 15:00:24  2020-10-13 03:10:07    10.000            0.000               0.000  2021      2          3          42  Thursday

# ÖZELLİK ETKİLEŞİMLERİ (FEATURE INTERACTION)

özellik etkileşimi değişkenlerin birbiri ile etkileşimine denmektedir. örneğin iki değişkenin çarpılması, toplanması, birdeğişkenin karesinin küpünün alınması gibi değişkenlerle etkileşim kurmak demektir.

In [37]:
df = load()
df.head()

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S

In [38]:
#örn yaş değişkeni ile pclası çarpıyorum
df["NEW_AGE_PCLASS"] = df["Age"] * df["Pclass"]
# burda dikkat etmem gereken şey örn pclass 1 ile 3 arasında ya yaş değişşkeni de öyle olsun
#burada bunu çarpmam örn refah açısından bir şey ifadeediyor olabilir, çarpılan sonunç 
#örn yaşı büyük olup pclassı 1 olanla yaşı küçük olup pclassı 3 olan biri arasında fark ifade etmektedir
# yani bu çarpımlar bir teoriye karşılık olarak oluşturulmadır. buradan sonuç olarak 
# yaşı küçük olup 1. sınıfta yolculuk edenleri bulabilmektir ya da yaşı büyük yine de 3. sınıfta acaba refah seviyesi mi düşük
# diye bir tez ortaya koymaktır.
df.head()

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked  NEW_AGE_PCLASS
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S          66.000
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C          38.000
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S          78.000
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S          35.000
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S         105.000

In [41]:
df["NEW_FAMILY_SIZE"] = df["SibSp"] + df["Parch"] + 1
df.head() #gemideki aile bireyleri sayılarını bulabiliriz, aile sayısı ve artı kendisi şeklinde

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked  NEW_AGE_PCLASS  NEW_FAMILY_SIZE
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S          66.000                2
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C          38.000                2
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S          78.000                1
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S          35.000                2
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S         105.000                1

belirli bir kategorik ya da sayısal dğişkenlerin etkieşimlerine de flagler atılabilir. bu noktalara da değişkenler oluşturulabilir. peki ne demek bu, mesela yaşı 21den küçük erkekler, ya da yaşı 50den büyük kadınlar

In [42]:
df.loc[(df["Sex"] == "male") & (df["Age"] <= 21), "NEW_SEX_CAT"] = "youngmale"
# male olanları ve yaşı 21den küçük eşit olanları bu isimde bir değişkene arayıp bu şekilde isimlendir diyorum
df.head()

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked  NEW_AGE_PCLASS  NEW_FAMILY_SIZE NEW_SEX_CAT
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S          66.000                2         NaN
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C          38.000                2         NaN
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S          78.000                1         NaN
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S          35.000                2         NaN
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S         105.000                1         NaN

In [43]:
df.loc[(df["Sex"] == "male") & (df["Age"] > 22) & (df["Age"] <= 50), "NEW_SEX_CAT"] = "maturemale"
#cisiyeti erkek olan ve yaşı 21den büyük ve 50den küçük eşit olanalrı seç ve bu eşkilde isimlendir.

In [44]:
df.loc[(df["Sex"] == "male") & (df["Age"] > 50), "NEW_SEX_CAT"] = "seniormale"
#yaşı 50den büyük olanlara senior de dedim.
df.head()

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked  NEW_AGE_PCLASS  NEW_FAMILY_SIZE NEW_SEX_CAT
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S          66.000                2         NaN
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C          38.000                2         NaN
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S          78.000                1         NaN
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S          35.000                2         NaN
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S         105.000                1  maturemale

aynı işi kadınlar için de yapıyorum

In [45]:
df.groupby("NEW_SEX_CAT")["Survived"].mean()
#NEW_SEX_CAT göre survived değişkenini groupbya alıp ortalamsını alıyorum

NEW_SEX_CAT
maturemale   0.207
seniormale   0.128
youngmale    0.250
Name: Survived, dtype: float64

In [46]:
#olgun kadınları yaptığımı varsaydım ve hayatta kalma oranları 0.74 çıkarken 
#seniormalelerin hayatta kalma oranı sadece 0.128 dir yani bu şekilde mantıklı is
#istatistiksel sonuçlar elde edebilirim.

# 5 ) UYGULAMA

In [47]:
#bu bölümde titanic verisini uçtan uca tamamen ele alacağız, öğrendiğimiz tüm
#metodları uygulayacağız.

df = load()

In [48]:
df.shape

(891, 12)

In [50]:
df.head()

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S

In [51]:
#bu veri setinde amaç insanların hayatta kalıp kalamayacağını modellemeye çalışmaktır.
#biz de modelleme öncesi gereken tüm işlemleri yapacağız.

In [52]:
#verideki tüm harfleri büyüteceğiz çünkü tek formatta olmasını istiyorum

df.columns = [col.upper() for col in df.columns] #kolonları gez ve büyült diyorum

In [53]:
#1. adım Feature Engineering (Değişken Mühendisliği)

# yaptıklarım var zaten
#cabinbooldan seniorfemaleye kadar son yaptığım.
#önce aykırı değerler sonra eksik değerleri işledi
#bir değişkendeki eksiklik ondan türetilen değişkenlerde de devam eder.
#artık standartlaştırma bölümünden sonra model aşamasına geçceğiz.

In [54]:
#kalan kısımları sonra yazacağım.