In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
pd.set_option("display.max_columns", None) #. ifadesi, DataFrame'lerinizi gösterirken maksimum sütun sayısını sınırsız yapar. 
#Yani, DataFrame'lerinizin tüm sütunlarını kırpma olmadan görüntülenmesini sağlar.Bu durumda, None değeri, 
#DataFrame'lerin tüm sütunlarını ekrana sığdırmak anlamına gelir. Yani, hiçbir sütun kesilmeden veya kırpılmadan tamamıyla görüntülenir.
pd.set_option("display.width", 2000)

In [3]:
df = pd.read_excel("yemek-sepeti-2.xlsx")
df

       order_id          order_time order_city    order_area order_kitchen  order_restaurant_id  order_size_TRY preffered_payment_method  isSeamless  isnotSeamless   contact_reason_CSRLevel3 contact_reason_MainGroup  isContact  isSelfService  ContactCSAT  SelfServiceCSAT  NPS-Q-Score
0       9450303 2024-07-26 01:26:02   İstanbul    Sancaktepe      Kahvaltı               723542             103           Online Payment           1              0                          -                        -          0              0            0                0            8
1       3091190 2024-02-24 13:44:21   İstanbul          Şile         Pizza               207622              80                     Cash           1              0                          -                        -          0              0            0                0            4
2       8040029 2024-01-06 19:26:41   İstanbul        Beykoz          Pide                35740             168                     Cash           1              0                          -                        -          0              0            0                0           10
3       9828010 2024-08-23 16:32:36   İstanbul      Bakırköy        Burger               614173             104        Credit/Debit Card           1              0                          -                        -          0              0            0                0            8
4       7887475 2024-07-19 09:23:03   İstanbul  Büyükçekmece        Burger               818521             415           Online Payment           1              0                          -                        -          0              0            0                0           10
...         ...                 ...        ...           ...           ...                  ...             ...                      ...         ...            ...                        ...                      ...        ...            ...          ...              ...          ...
49995   6823941 2024-03-21 14:58:48   İstanbul      Ataşehir          Pide               529907             209        Credit/Debit Card           1              0                          -                        -          0              0            0                0            5
49996   1208839 2024-02-11 09:57:30   İstanbul        Kartal      Çiğköfte               271839              80           Online Payment           1              0                          -                        -          0              0            0                0            8
49997   1657925 2024-05-17 13:52:45   İstanbul      Ümraniye        Burger               869624             122           Online Payment           1              0                          -                        -          0              0            0                0            8
49998   6576510 2024-02-15 12:52:51   İstanbul       Üsküdar        Burger               537218             488                Meal Card           1              0                          -                        -          0              0            0                0           10
49999    927645 2024-06-27 16:58:41   İstanbul         Fatih          Pide               331232             255                     Cash           0              1  Request: accidental order    Cancellation Requests          0              1            0                5            7

[50000 rows x 17 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  50000 non-null  int64
 1   order_time                50000 non-null  datetime64[ns]
 2   order_city                50000 non-null  object
 3   order_area                50000 non-null  object
 4   order_kitchen             50000 non-null  object
 5   order_restaurant_id       50000 non-null  int64
 6   order_size_TRY            50000 non-null  int64
 7   preffered_payment_method  50000 non-null  object
 8   isSeamless                50000 non-null  int64
 9   isnotSeamless             50000 non-null  int64
 10  contact_reason_CSRLevel3  50000 non-null  object
 11  contact_reason_MainGroup  50000 non-null  object
 12  isContact                 50000 non-null  int64
 13  isSelfService             50000 non-null  int64
 14  ContactCSAT               50000 non-null  int64
 15  SelfServiceCSAT           50000 non-null  int64
 16  NPS-Q-Score               50000 non-null  int64
dtypes: datetime64[ns](1), int64(10), object(6)
memory usage: 6.5+ MB

In [5]:
# ilk etapta kolonlarımızı tanıyıp labellarımıza bakıyoruz

In [6]:
df["isSeamless"].value_counts() #sorunsuz sipariş gerçekleşme oranı

1    37310
0    12690
Name: isSeamless, dtype: int64

In [7]:
df["isnotSeamless"].value_counts() #sorunlu sipariş gerçkeleşme durumu
# bu değişkenin 1 durumu üstteki değişkenin 0 durumuna eşit olmalıdır.

0    37310
1    12690
Name: isnotSeamless, dtype: int64

In [8]:
df["contact_reason_CSRLevel3"].value_counts() #problemleri siparişlerin nedenleri

-                                                37310
Complaint about severe delay                      1132
Wrong item                                        1072
Missing item                                      1067
Order marked as delivered but didn't receive       933
Complaint about moderate delay                     912
Restaurant hasn't started preparing the food       907
Request: accidental order                          774
Complaint about extreme delay                      773
Request: order is late-does not want to wait       704
Request: order will take longer than expected      573
Food quality                                       566
Spilled food                                       345
Food temperature                                   343
Partner cancellation                               337
Request: voucher not applied                       245
Request: changed mind                              239
Cooking instructions were not followed             238
Delivery instructions                              224
Request: Partner closed for pickup                 209
Request: duplicated order                          208
Payment method                                     127
Food items                                         116
Address                                            112
Cooking instructions                               111
Information request                                111
Invoice missing                                    106
Inappropriate behaviour                            105
Delivery time/date                                 101
Name: contact_reason_CSRLevel3, dtype: int64

In [9]:
df["contact_reason_MainGroup"].value_counts() #problemli siparişlerin sınıflandırılması

-                                      37310
Order Delay                             4657
Cancellation Requests                   2952
Missing Item & Wrong Item/Order         2245
Product & Service Dissatisfaction       1492
Adding Note & Delivery Instructions      791
Other Reasons                            553
Name: contact_reason_MainGroup, dtype: int64

In [10]:
df["isContact"].value_counts() # contact direkt olarak insan bir müşteri temsilcisiyle görüşen sayısı

0    47495
1     2505
Name: isContact, dtype: int64

isnotseamles ile seamlesın toplamı isselfservicein toplamına eşit olmalı çünkü sorunlu sipariş sayısı gerçek temsilci ile bot temsilci sayısına eşit olup problemli müşteri sayısına dahil olan herkes iletişime geçmiştir.

In [11]:
df["isSelfService"].value_counts() #bir bot ile görüşen sayısı

0    39815
1    10185
Name: isSelfService, dtype: int64

In [12]:
df["ContactCSAT"].value_counts() #gerçek insanla görüşüp puan verenler

0    47495
3      814
2      548
1      534
5      322
4      287
Name: ContactCSAT, dtype: int64

In [13]:
df["SelfServiceCSAT"].value_counts() #botla görşüp onu puanlayanlar

0    39815
2     3552
1     1813
5     1640
4     1630
3     1550
Name: SelfServiceCSAT, dtype: int64

In [14]:
df["NPS-Q-Score"].value_counts() # aşağıda açıklaması var

10    16869
8     12613
9      5696
4      4597
5      3657
6      2984
7      2630
3       556
1       204
2       194
Name: NPS-Q-Score, dtype: int64

nps skor = destekleyicilerin sayısı (9-10 puan alanlar) - eleştirmenlerin sayısı (1-6) / toplam yanıt verenlerin sayısı

7-8 arası puan verenler pasiflerdir. NPS'yi şikayet nedenlerine göre dağılım gibi çeşitli kategorilere göre derinlemesine inceleyebiliriz.

In [15]:
notseamles = df[df["isnotSeamless"] == 1]
notseamles

       order_id          order_time order_city    order_area order_kitchen  order_restaurant_id  order_size_TRY preffered_payment_method  isSeamless  isnotSeamless                      contact_reason_CSRLevel3             contact_reason_MainGroup  isContact  isSelfService  ContactCSAT  SelfServiceCSAT  NPS-Q-Score
13      6638263 2024-04-17 11:31:39   İstanbul      Bakırköy         Döner               611084             280           Online Payment           0              1  Order marked as delivered but didn't receive                          Order Delay          0              1            0                2            9
16      3428331 2024-04-14 11:50:43   İstanbul    Bayrampaşa        Burger               138139             609           Online Payment           0              1                                    Wrong item      Missing Item & Wrong Item/Order          0              1            0                2            7
24      6371640 2024-04-01 00:40:47   İstanbul  Küçükçekmece          Pide               443465             441           Online Payment           0              1                                    Wrong item      Missing Item & Wrong Item/Order          0              1            0                4            6
25      3453042 2024-03-14 14:36:10   İstanbul       Maltepe      Çiğköfte                76044             696           Online Payment           0              1                                  Food quality    Product & Service Dissatisfaction          0              1            0                2            8
27      4615200 2024-04-03 00:58:21   İstanbul      Beşiktaş        Burger               512524             529           Online Payment           0              1                                    Food items  Adding Note & Delivery Instructions          0              1            0                2            9
...         ...                 ...        ...           ...           ...                  ...             ...                      ...         ...            ...                                           ...                                  ...        ...            ...          ...              ...          ...
49979   2586508 2024-04-23 11:21:46   İstanbul       Silivri        Burger                97267             167                Meal Card           0              1                          Partner cancellation                        Other Reasons          0              1            0                3            7
49981   1893023 2024-01-02 22:19:01   İstanbul          Şile  Ev Yemekleri               325125             351                     Cash           0              1                     Request: accidental order                Cancellation Requests          0              1            0                2            2
49982   6922966 2024-03-15 14:02:54   İstanbul      Güngören        Burger               160881             248           Online Payment           0              1  Order marked as delivered but didn't receive                          Order Delay          0              1            0                1            6
49983   8090904 2024-06-21 07:06:30   İstanbul      Güngören        Burger               691491             309        Credit/Debit Card           0              1                       Inappropriate behaviour                        Other Reasons          0              1            0                4            3
49999    927645 2024-06-27 16:58:41   İstanbul         Fatih          Pide               331232             255                     Cash           0              1                     Request: accidental order                Cancellation Requests          0              1            0                5            7

[12690 rows x 17 columns]

In [16]:
notseamles.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12690 entries, 13 to 49999
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  12690 non-null  int64
 1   order_time                12690 non-null  datetime64[ns]
 2   order_city                12690 non-null  object
 3   order_area                12690 non-null  object
 4   order_kitchen             12690 non-null  object
 5   order_restaurant_id       12690 non-null  int64
 6   order_size_TRY            12690 non-null  int64
 7   preffered_payment_method  12690 non-null  object
 8   isSeamless                12690 non-null  int64
 9   isnotSeamless             12690 non-null  int64
 10  contact_reason_CSRLevel3  12690 non-null  object
 11  contact_reason_MainGroup  12690 non-null  object
 12  isContact                 12690 non-null  int64
 13  isSelfService             12690 non-null  int64
 14  ContactCSAT               12690 non-null  int64
 15  SelfServiceCSAT           12690 non-null  int64
 16  NPS-Q-Score               12690 non-null  int64
dtypes: datetime64[ns](1), int64(10), object(6)
memory usage: 1.7+ MB

In [17]:
def cat_summary(dataframe, col_name):
    print(pd.DataFrame({col_name: dataframe[col_name].value_counts(),
                        "% ORAN" : 100 * dataframe[col_name].value_counts() / len(dataframe)}))
    print("#################################")
    
cat_summary(notseamles, "contact_reason_CSRLevel3")

                                               contact_reason_CSRLevel3    % ORAN
Complaint about severe delay                                       1132  8.920410
Wrong item                                                         1072  8.447597
Missing item                                                       1067  8.408195
Order marked as delivered but didn't receive                        933  7.352246
Complaint about moderate delay                                      912  7.186761
Restaurant hasn't started preparing the food                        907  7.147360
Request: accidental order                                           774  6.099291
Complaint about extreme delay                                       773  6.091411
Request: order is late-does not want to wait                        704  5.547675
Request: order will take longer than expected                       573  4.515366
Food quality                                                        566  4.460205
Spilled food                                                        345  2.718676
Food temperature                                                    343  2.702916
Partner cancellation                                                337  2.655634
Request: voucher not applied                                        245  1.930654
Request: changed mind                                               239  1.883373
Cooking instructions were not followed                              238  1.875493
Delivery instructions                                               224  1.765169
Request: Partner closed for pickup                                  209  1.646966
Request: duplicated order                                           208  1.639086
Payment method                                                      127  1.000788
Food items                                                          116  0.914106
Address                                                             112  0.882585
Information request                                                 111  0.874704
Cooking instructions                                                111  0.874704
Invoice missing                                                     106  0.835303
Inappropriate behaviour                                             105  0.827423
Delivery time/date                                                  101  0.795902
#################################

In [18]:
def cat_summary(dataframe, col_name):
    print(pd.DataFrame({col_name: dataframe[col_name].value_counts(),
                        "% ORAN" : 100 * dataframe[col_name].value_counts() / len(dataframe)}))
    print("#################################")
    
cat_summary(notseamles, "contact_reason_MainGroup")

                                     contact_reason_MainGroup     % ORAN
Order Delay                                              4657  36.698188
Cancellation Requests                                    2952  23.262411
Missing Item & Wrong Item/Order                          2245  17.691095
Product & Service Dissatisfaction                        1492  11.757289
Adding Note & Delivery Instructions                       791   6.233255
Other Reasons                                             553   4.357762
#################################

In [19]:
notseamles[(notseamles["contact_reason_MainGroup"] == "Order Delay") & (notseamles["isSelfService"] == 1)].value_counts().sum()

3739

In [20]:
def mainde_dolas(maingroup_label, selfservis):
    
    selfservis = notseamles[(notseamles["contact_reason_MainGroup"] == maingroup_label) & (notseamles["isSelfService"] == selfservis)]
    
    """
    burada maingroup labelları dolaşılıp self servisi 1 olanlar ve 0 olanların oranları bulunmaya çalışılacaktır
    """
    return selfservis

In [21]:
order_delay = mainde_dolas("Order Delay", 1)
order_delay.value_counts().sum()

3739

In [22]:
def mainde_dolas(maingroup_label, selfservis):
    # Belirli bir MainGroup ve selfservis değerine sahip verileri filtreler
    filtered_df = notseamles[(notseamles["contact_reason_MainGroup"] == maingroup_label) & 
                             (notseamles["isSelfService"] == selfservis)]
    return filtered_df

# contact_reason_MainGroup'taki unique değerler üzerinde döngü
for label in notseamles["contact_reason_MainGroup"].unique():
    # selfservis değeri 1 olanlar için
    df_selfservis_1 = mainde_dolas(label, 1)
    # selfservis değeri 0 olanlar için
    df_selfservis_0 = mainde_dolas(label, 0)

    # Her bir grup için adet ve yüzde hesaplama
    total_count = len(notseamles[notseamles["contact_reason_MainGroup"] == label])
    count_selfservis_1 = len(df_selfservis_1)
    count_selfservis_0 = len(df_selfservis_0)

    # Yüzdelik oranları hesaplama
    percentage_selfservis_1 = (count_selfservis_1 / total_count) * 100
    percentage_selfservis_0 = (count_selfservis_0 / total_count) * 100

    # Sonuçları yazdırma
    print(f"Label: {label}")
    print(f"  Toplam Adet: {total_count}")
    print(f"  SelfServis 1: {count_selfservis_1} ({percentage_selfservis_1:.2f}%)")
    print(f"  SelfServis 0: {count_selfservis_0} ({percentage_selfservis_0:.2f}%)")
    print("-" * 50)

Label: Order Delay
  Toplam Adet: 4657
  SelfServis 1: 3739 (80.29%)
  SelfServis 0: 918 (19.71%)
--------------------------------------------------
Label: Missing Item & Wrong Item/Order
  Toplam Adet: 2245
  SelfServis 1: 1791 (79.78%)
  SelfServis 0: 454 (20.22%)
--------------------------------------------------
Label: Product & Service Dissatisfaction
  Toplam Adet: 1492
  SelfServis 1: 1185 (79.42%)
  SelfServis 0: 307 (20.58%)
--------------------------------------------------
Label: Adding Note & Delivery Instructions
  Toplam Adet: 791
  SelfServis 1: 642 (81.16%)
  SelfServis 0: 149 (18.84%)
--------------------------------------------------
Label: Cancellation Requests
  Toplam Adet: 2952
  SelfServis 1: 2375 (80.45%)
  SelfServis 0: 577 (19.55%)
--------------------------------------------------
Label: Other Reasons
  Toplam Adet: 553
  SelfServis 1: 453 (81.92%)
  SelfServis 0: 100 (18.08%)
--------------------------------------------------

In [23]:
def csrlevel_3_dolas(maingroup_label, selfservis):
    # Belirli bir MainGroup ve selfservis değerine sahip verileri filtreler
    filtered_df = notseamles[(notseamles["contact_reason_CSRLevel3"] == maingroup_label) & 
                             (notseamles["isSelfService"] == selfservis)]
    return filtered_df

# contact_reason_MainGroup'taki unique değerler üzerinde döngü
for label in notseamles["contact_reason_CSRLevel3"].unique():
    # selfservis değeri 1 olanlar için
    df_selfservis_1 = csrlevel_3_dolas(label, 1)
    # selfservis değeri 0 olanlar için
    df_selfservis_0 = csrlevel_3_dolas(label, 0)

    # Her bir grup için adet ve yüzde hesaplama
    total_count = len(notseamles[notseamles["contact_reason_CSRLevel3"] == label])
    count_selfservis_1 = len(df_selfservis_1)
    count_selfservis_0 = len(df_selfservis_0)

    # Yüzdelik oranları hesaplama
    percentage_selfservis_1 = (count_selfservis_1 / total_count) * 100
    percentage_selfservis_0 = (count_selfservis_0 / total_count) * 100

    # Sonuçları yazdırma
    print(f"Label: {label}")
    print(f"  Toplam Adet: {total_count}")
    print(f"  SelfServis 1: {count_selfservis_1} ({percentage_selfservis_1:.2f}%)")
    print(f"  SelfServis 0: {count_selfservis_0} ({percentage_selfservis_0:.2f}%)")
    print("-" * 50)

Label: Order marked as delivered but didn't receive
  Toplam Adet: 933
  SelfServis 1: 752 (80.60%)
  SelfServis 0: 181 (19.40%)
--------------------------------------------------
Label: Wrong item
  Toplam Adet: 1072
  SelfServis 1: 852 (79.48%)
  SelfServis 0: 220 (20.52%)
--------------------------------------------------
Label: Food quality
  Toplam Adet: 566
  SelfServis 1: 450 (79.51%)
  SelfServis 0: 116 (20.49%)
--------------------------------------------------
Label: Food items
  Toplam Adet: 116
  SelfServis 1: 93 (80.17%)
  SelfServis 0: 23 (19.83%)
--------------------------------------------------
Label: Request: order is late-does not want to wait
  Toplam Adet: 704
  SelfServis 1: 568 (80.68%)
  SelfServis 0: 136 (19.32%)
--------------------------------------------------
Label: Missing item
  Toplam Adet: 1067
  SelfServis 1: 858 (80.41%)
  SelfServis 0: 209 (19.59%)
--------------------------------------------------
Label: Request: accidental order
  Toplam Adet: 774
  SelfServis 1: 611 (78.94%)
  SelfServis 0: 163 (21.06%)
--------------------------------------------------
Label: Complaint about moderate delay
  Toplam Adet: 912
  SelfServis 1: 741 (81.25%)
  SelfServis 0: 171 (18.75%)
--------------------------------------------------
Label: Delivery instructions
  Toplam Adet: 224
  SelfServis 1: 180 (80.36%)
  SelfServis 0: 44 (19.64%)
--------------------------------------------------
Label: Request: order will take longer than expected
  Toplam Adet: 573
  SelfServis 1: 469 (81.85%)
  SelfServis 0: 104 (18.15%)
--------------------------------------------------
Label: Complaint about extreme delay
  Toplam Adet: 773
  SelfServis 1: 619 (80.08%)
  SelfServis 0: 154 (19.92%)
--------------------------------------------------
Label: Information request
  Toplam Adet: 111
  SelfServis 1: 87 (78.38%)
  SelfServis 0: 24 (21.62%)
--------------------------------------------------
Label: Payment method
  Toplam Adet: 127
  SelfServis 1: 105 (82.68%)
  SelfServis 0: 22 (17.32%)
--------------------------------------------------
Label: Restaurant hasn't started preparing the food
  Toplam Adet: 907
  SelfServis 1: 715 (78.83%)
  SelfServis 0: 192 (21.17%)
--------------------------------------------------
Label: Spilled food
  Toplam Adet: 345
  SelfServis 1: 279 (80.87%)
  SelfServis 0: 66 (19.13%)
--------------------------------------------------
Label: Complaint about severe delay
  Toplam Adet: 1132
  SelfServis 1: 912 (80.57%)
  SelfServis 0: 220 (19.43%)
--------------------------------------------------
Label: Cooking instructions were not followed
  Toplam Adet: 238
  SelfServis 1: 192 (80.67%)
  SelfServis 0: 46 (19.33%)
--------------------------------------------------
Label: Request: duplicated order
  Toplam Adet: 208
  SelfServis 1: 166 (79.81%)
  SelfServis 0: 42 (20.19%)
--------------------------------------------------
Label: Food temperature
  Toplam Adet: 343
  SelfServis 1: 264 (76.97%)
  SelfServis 0: 79 (23.03%)
--------------------------------------------------
Label: Request: voucher not applied
  Toplam Adet: 245
  SelfServis 1: 189 (77.14%)
  SelfServis 0: 56 (22.86%)
--------------------------------------------------
Label: Cooking instructions
  Toplam Adet: 111
  SelfServis 1: 86 (77.48%)
  SelfServis 0: 25 (22.52%)
--------------------------------------------------
Label: Request: Partner closed for pickup
  Toplam Adet: 209
  SelfServis 1: 173 (82.78%)
  SelfServis 0: 36 (17.22%)
--------------------------------------------------
Label: Partner cancellation
  Toplam Adet: 337
  SelfServis 1: 284 (84.27%)
  SelfServis 0: 53 (15.73%)
--------------------------------------------------
Label: Address
  Toplam Adet: 112
  SelfServis 1: 93 (83.04%)
  SelfServis 0: 19 (16.96%)
--------------------------------------------------
Label: Invoice missing
  Toplam Adet: 106
  SelfServis 1: 81 (76.42%)
  SelfServis 0: 25 (23.58%)
--------------------------------------------------
Label: Delivery time/date
  Toplam Adet: 101
  SelfServis 1: 85 (84.16%)
  SelfServis 0: 16 (15.84%)
--------------------------------------------------
Label: Request: changed mind
  Toplam Adet: 239
  SelfServis 1: 199 (83.26%)
  SelfServis 0: 40 (16.74%)
--------------------------------------------------
Label: Inappropriate behaviour
  Toplam Adet: 105
  SelfServis 1: 82 (78.10%)
  SelfServis 0: 23 (21.90%)
--------------------------------------------------

insanlar oran olarak en az "Invoice missing" ve "Food temperature" da selfservisi kullanmışlardır ve gerçek bir temsilci ile konuşmak istemişlerdir. yani insanlar self servisten en az memnun kaldıkları kısım bu labellar olabilir diyebilirim.

In [24]:
notseamles

       order_id          order_time order_city    order_area order_kitchen  order_restaurant_id  order_size_TRY preffered_payment_method  isSeamless  isnotSeamless                      contact_reason_CSRLevel3             contact_reason_MainGroup  isContact  isSelfService  ContactCSAT  SelfServiceCSAT  NPS-Q-Score
13      6638263 2024-04-17 11:31:39   İstanbul      Bakırköy         Döner               611084             280           Online Payment           0              1  Order marked as delivered but didn't receive                          Order Delay          0              1            0                2            9
16      3428331 2024-04-14 11:50:43   İstanbul    Bayrampaşa        Burger               138139             609           Online Payment           0              1                                    Wrong item      Missing Item & Wrong Item/Order          0              1            0                2            7
24      6371640 2024-04-01 00:40:47   İstanbul  Küçükçekmece          Pide               443465             441           Online Payment           0              1                                    Wrong item      Missing Item & Wrong Item/Order          0              1            0                4            6
25      3453042 2024-03-14 14:36:10   İstanbul       Maltepe      Çiğköfte                76044             696           Online Payment           0              1                                  Food quality    Product & Service Dissatisfaction          0              1            0                2            8
27      4615200 2024-04-03 00:58:21   İstanbul      Beşiktaş        Burger               512524             529           Online Payment           0              1                                    Food items  Adding Note & Delivery Instructions          0              1            0                2            9
...         ...                 ...        ...           ...           ...                  ...             ...                      ...         ...            ...                                           ...                                  ...        ...            ...          ...              ...          ...
49979   2586508 2024-04-23 11:21:46   İstanbul       Silivri        Burger                97267             167                Meal Card           0              1                          Partner cancellation                        Other Reasons          0              1            0                3            7
49981   1893023 2024-01-02 22:19:01   İstanbul          Şile  Ev Yemekleri               325125             351                     Cash           0              1                     Request: accidental order                Cancellation Requests          0              1            0                2            2
49982   6922966 2024-03-15 14:02:54   İstanbul      Güngören        Burger               160881             248           Online Payment           0              1  Order marked as delivered but didn't receive                          Order Delay          0              1            0                1            6
49983   8090904 2024-06-21 07:06:30   İstanbul      Güngören        Burger               691491             309        Credit/Debit Card           0              1                       Inappropriate behaviour                        Other Reasons          0              1            0                4            3
49999    927645 2024-06-27 16:58:41   İstanbul         Fatih          Pide               331232             255                     Cash           0              1                     Request: accidental order                Cancellation Requests          0              1            0                5            7

[12690 rows x 17 columns]

In [25]:
notseamles["SelfServiceCSAT"].value_counts()# self serviscsat labelları yani puanlamaları

2    3552
0    2505
1    1813
5    1640
4    1630
3    1550
Name: SelfServiceCSAT, dtype: int64

In [26]:
notseamles[(notseamles["isSelfService"] == 1) & (notseamles["SelfServiceCSAT"] == 1)].value_counts().sum()
notseamles[(notseamles["isSelfService"] == 1) & (notseamles["SelfServiceCSAT"] == 2)].value_counts().sum()
notseamles[(notseamles["isSelfService"] == 1) & (notseamles["SelfServiceCSAT"] == 3)].value_counts().sum()
notseamles[(notseamles["isSelfService"] == 1) & (notseamles["SelfServiceCSAT"] == 4)].value_counts().sum()
notseamles[(notseamles["isSelfService"] == 1) & (notseamles["SelfServiceCSAT"] == 5)].value_counts().sum()
#notseamles[(notseamles["isSelfService"] == 1) & (notseamles["SelfServiceCSAT"] == 0)].value_counts().sum()

# self servisi 1 olup yani botla konuşup 0 puan veren ya da puanlamayan kimse bulunmamakta

1640

In [27]:
notseamles[(notseamles["isSelfService"] == 1) & (notseamles["SelfServiceCSAT"] == 1)].value_counts().sum()

1813

In [28]:
def self_servis(self_cat):
    self_don = notseamles[(notseamles["isSelfService"] == 1) & (notseamles["SelfServiceCSAT"] == self_cat)]
    
    return self_don

In [29]:
self_ser_cat_1 = self_servis(1) #self servisi 1 olup puanı 1 olanlar
self_ser_cat_2 = self_servis(2) #self servisi 1 olup puanı 2 olanlar
self_ser_cat_3 = self_servis(3) #self servisi 1 olup puanı 3 olanlar
self_ser_cat_4 = self_servis(4) #self servisi 1 olup puanı 4 olanlar
self_ser_cat_5 = self_servis(5) #self servisi 1 olup puanı 5 olanlar

In [30]:
self_ser_cat_1

       order_id          order_time order_city  order_area order_kitchen  order_restaurant_id  order_size_TRY preffered_payment_method  isSeamless  isnotSeamless                      contact_reason_CSRLevel3 contact_reason_MainGroup  isContact  isSelfService  ContactCSAT  SelfServiceCSAT  NPS-Q-Score
49      2180498 2024-04-29 06:33:40   İstanbul     Beyoğlu         Pizza               876865             354        Credit/Debit Card           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            6
164     3321365 2024-08-30 19:01:22   İstanbul    Ümraniye        Burger               676328             417                     Cash           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            5
169     6291085 2024-08-08 19:44:11   İstanbul    Esenyurt    Soğuk Meze               534232             164        Credit/Debit Card           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            5
208     2700831 2024-03-14 03:06:54   İstanbul     Üsküdar      Kahvaltı               315151             528           Online Payment           0              1                 Complaint about extreme delay              Order Delay          0              1            0                1            8
280     8348059 2024-07-07 18:15:32   İstanbul    Çekmeköy          Pide               231209              97           Online Payment           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            2
...         ...                 ...        ...         ...           ...                  ...             ...                      ...         ...            ...                                           ...                      ...        ...            ...          ...              ...          ...
49914   5569721 2024-05-19 20:25:00   İstanbul  Sultangazi  Ev Yemekleri               921077             564        Credit/Debit Card           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            8
49929   5377498 2024-03-03 14:57:46   İstanbul     Üsküdar         Tatlı               975629              80           Online Payment           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            8
49956   4724098 2024-06-18 03:32:46   İstanbul    Çekmeköy          Pide               230292             191           Online Payment           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            5
49962   3945270 2024-01-02 05:22:40   İstanbul     Kadıköy         Pizza               780135             504        Credit/Debit Card           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            9
49982   6922966 2024-03-15 14:02:54   İstanbul    Güngören        Burger               160881             248           Online Payment           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            6

[1813 rows x 17 columns]

In [31]:
self_ser_cat_1["order_area"].nunique()
#"""self_ser_cat_2["order_area"].value_counts()
#self_ser_cat_3["order_area"].nunique()"""

39

## AREAYA GÖRE KİTCHEN

#### self_ser_cat_1  kitchen

self servisi 1 olup puanı 1 olanlar

In [32]:
# order_area sütununa göre gruplandır, toplamları hesapla ve en büyük 5 alanı bul
top_5_areas = self_ser_cat_1.groupby('order_area').size().nlargest(5).index

# Bu 5 alan için order_kitchen sütunundaki en çok kullanılan değerleri bulalım
for area in top_5_areas:
    print(f"Order Area: {area}")
    
    # İlgili alan için order_kitchen frekanslarını bul
    kitchen_counts = self_ser_cat_1[self_ser_cat_1['order_area'] == area]['order_kitchen'].value_counts()
    
    # En çok kullanılanları yazdır
    print(kitchen_counts.head())  # İlk 5'i göstermek için .head() kullanıyoruz
    print("\n")

Order Area: Ümraniye
Pide      13
Pizza     12
Burger    11
Döner      9
Tatlı      7
Name: order_kitchen, dtype: int64


Order Area: Bakırköy
Pizza         13
Burger        12
Pide          12
Tatlı          8
Soğuk Meze     4
Name: order_kitchen, dtype: int64


Order Area: Çatalca
Burger          17
Pide            11
Pizza           10
Döner            6
Ev Yemekleri     4
Name: order_kitchen, dtype: int64


Order Area: Adalar
Pide      15
Pizza     11
Burger     8
Tatlı      6
Döner      5
Name: order_kitchen, dtype: int64


Order Area: Kadıköy
Pizza     15
Burger    10
Döner      7
Pide       5
Tatlı      5
Name: order_kitchen, dtype: int64

In [33]:
self_ser_cat_1[self_ser_cat_1['order_area'] == "Ümraniye"]['order_kitchen'].value_counts() #üstteki kodun doğruluğunu kontrol
#etmek için kodu elimizle tekrardan yazıyoruz ve dopru olduğunu görüyoruz.

Pide            13
Pizza           12
Burger          11
Döner            9
Tatlı            7
Soğuk Meze       4
Kahvaltı         3
Çiğköfte         1
Ev Yemekleri     1
Name: order_kitchen, dtype: int64

#### self_ser_cat_2 kitvhen

self servisi 1 olup puanı 2 olanlar

In [34]:
# order_area sütununa göre gruplandır, toplamları hesapla ve en büyük 5 alanı bul
top_5_areas = self_ser_cat_2.groupby('order_area').size().nlargest(5).index

# Bu 5 alan için order_kitchen sütunundaki en çok kullanılan değerleri bulalım
for area in top_5_areas:
    print(f"Order Area: {area}")
    
    # İlgili alan için order_kitchen frekanslarını bul
    kitchen_counts = self_ser_cat_2[self_ser_cat_2['order_area'] == area]['order_kitchen'].value_counts()
    
    # En çok kullanılanları yazdır
    print(kitchen_counts.head())  # İlk 5'i göstermek için .head() kullanıyoruz
    print("\n")

Order Area: Gaziosmanpaşa
Pide      27
Pizza     23
Burger    21
Döner     13
Tatlı     12
Name: order_kitchen, dtype: int64


Order Area: Fatih
Pide        21
Burger      19
Pizza       18
Çiğköfte    13
Tatlı       12
Name: order_kitchen, dtype: int64


Order Area: Başakşehir
Pide      22
Pizza     22
Burger    21
Tatlı     11
Döner      9
Name: order_kitchen, dtype: int64


Order Area: Çekmeköy
Pizza     20
Pide      19
Burger    18
Tatlı     14
Döner     13
Name: order_kitchen, dtype: int64


Order Area: Beyoğlu
Pide      21
Burger    21
Pizza     19
Tatlı     12
Döner     12
Name: order_kitchen, dtype: int64

#### self_ser_cat_3 kitchen

self servisi 1 olup puanı 3 olanlar

In [35]:
# order_area sütununa göre gruplandır, toplamları hesapla ve en büyük 5 alanı bul
top_5_areas = self_ser_cat_3.groupby('order_area').size().nlargest(5).index

# Bu 5 alan için order_kitchen sütunundaki en çok kullanılan değerleri bulalım
for area in top_5_areas:
    print(f"Order Area: {area}")
    
    # İlgili alan için order_kitchen frekanslarını bul
    kitchen_counts = self_ser_cat_3[self_ser_cat_3['order_area'] == area]['order_kitchen'].value_counts()
    
    # En çok kullanılanları yazdır
    print(kitchen_counts.head())  # İlk 5'i göstermek için .head() kullanıyoruz
    print("\n")

Order Area: Bakırköy
Pide            15
Burger          11
Pizza            7
Ev Yemekleri     4
Tatlı            3
Name: order_kitchen, dtype: int64


Order Area: Silivri
Burger        13
Pizza          9
Tatlı          5
Soğuk Meze     5
Çiğköfte       5
Name: order_kitchen, dtype: int64


Order Area: Esenyurt
Pide      10
Pizza      7
Burger     7
Tatlı      5
Döner      5
Name: order_kitchen, dtype: int64


Order Area: Çatalca
Pizza     11
Burger     9
Tatlı      8
Pide       5
Döner      4
Name: order_kitchen, dtype: int64


Order Area: Beşiktaş
Burger        13
Pizza          9
Pide           6
Soğuk Meze     5
Döner          4
Name: order_kitchen, dtype: int64

### AREAYA GÖRE PAYMENT

#### self_ser_cat_1 payment

self servisi 1 olup puanı 1 olanlar

In [36]:
# order_area sütununa göre gruplandır, toplamları hesapla ve en büyük 5 alanı bul
top_5_areas = self_ser_cat_1.groupby('order_area').size().nlargest(5).index

# Bu 5 alan için order_kitchen sütunundaki en çok kullanılan değerleri bulalım
for area in top_5_areas:
    print(f"Order Area: {area}")
    
    # İlgili alan için order_kitchen frekanslarını bul
    kitchen_counts = self_ser_cat_1[self_ser_cat_1['order_area'] == area]['preffered_payment_method'].value_counts()
    
    # En çok kullanılanları yazdır
    print(kitchen_counts.head())  # İlk 5'i göstermek için .head() kullanıyoruz
    print("\n")

Order Area: Ümraniye
Online Payment       26
Meal Card            18
Credit/Debit Card    12
Cash                  5
Name: preffered_payment_method, dtype: int64


Order Area: Bakırköy
Online Payment       31
Credit/Debit Card    12
Meal Card            10
Cash                  4
Name: preffered_payment_method, dtype: int64


Order Area: Çatalca
Online Payment       26
Meal Card            13
Credit/Debit Card    11
Cash                  7
Name: preffered_payment_method, dtype: int64


Order Area: Adalar
Online Payment       31
Credit/Debit Card    11
Meal Card             9
Cash                  4
Name: preffered_payment_method, dtype: int64


Order Area: Kadıköy
Online Payment       23
Meal Card            17
Credit/Debit Card    12
Cash                  3
Name: preffered_payment_method, dtype: int64

#### self_ser_cat_2 payment

self servisi 1 olup puanı 2 olanlar

In [37]:
# order_area sütununa göre gruplandır, toplamları hesapla ve en büyük 5 alanı bul
top_5_areas = self_ser_cat_2.groupby('order_area').size().nlargest(5).index

# Bu 5 alan için order_kitchen sütunundaki en çok kullanılan değerleri bulalım
for area in top_5_areas:
    print(f"Order Area: {area}")
    
    # İlgili alan için order_kitchen frekanslarını bul
    kitchen_counts = self_ser_cat_2[self_ser_cat_2['order_area'] == area]['preffered_payment_method'].value_counts()
    
    # En çok kullanılanları yazdır
    print(kitchen_counts.head())  # İlk 5'i göstermek için .head() kullanıyoruz
    print("\n")

Order Area: Gaziosmanpaşa
Online Payment       60
Meal Card            27
Credit/Debit Card    23
Cash                 10
Name: preffered_payment_method, dtype: int64


Order Area: Fatih
Online Payment       60
Meal Card            22
Credit/Debit Card    22
Cash                  6
Name: preffered_payment_method, dtype: int64


Order Area: Başakşehir
Online Payment       51
Credit/Debit Card    24
Meal Card            21
Cash                 11
Name: preffered_payment_method, dtype: int64


Order Area: Çekmeköy
Online Payment       56
Credit/Debit Card    26
Meal Card            19
Cash                  5
Name: preffered_payment_method, dtype: int64


Order Area: Beyoğlu
Online Payment       56
Credit/Debit Card    19
Meal Card            17
Cash                 11
Name: preffered_payment_method, dtype: int64

#### self_ser_cat_3 payment

self servisi 1 olup puanı 3 olanlar

In [38]:
# order_area sütununa göre gruplandır, toplamları hesapla ve en büyük 5 alanı bul
top_5_areas = self_ser_cat_3.groupby('order_area').size().nlargest(5).index

# Bu 5 alan için order_kitchen sütunundaki en çok kullanılan değerleri bulalım
for area in top_5_areas:
    print(f"Order Area: {area}")
    
    # İlgili alan için order_kitchen frekanslarını bul
    kitchen_counts = self_ser_cat_3[self_ser_cat_3['order_area'] == area]['preffered_payment_method'].value_counts()
    
    # En çok kullanılanları yazdır
    print(kitchen_counts.head())  # İlk 5'i göstermek için .head() kullanıyoruz
    print("\n")

Order Area: Bakırköy
Online Payment       19
Meal Card            14
Credit/Debit Card     9
Cash                  7
Name: preffered_payment_method, dtype: int64


Order Area: Silivri
Online Payment       22
Meal Card            12
Credit/Debit Card    10
Cash                  5
Name: preffered_payment_method, dtype: int64


Order Area: Esenyurt
Online Payment       23
Meal Card            14
Credit/Debit Card     6
Cash                  4
Name: preffered_payment_method, dtype: int64


Order Area: Çatalca
Online Payment       26
Credit/Debit Card     8
Cash                  8
Meal Card             5
Name: preffered_payment_method, dtype: int64


Order Area: Beşiktaş
Online Payment       21
Credit/Debit Card    12
Meal Card             8
Cash                  5
Name: preffered_payment_method, dtype: int64

## NPS SCORE DENEME

nps skor = destekleyicilerin sayısı (9-10 puan alanlar) - eleştirmenlerin sayısı (1-6) / toplam yanıt verenlerin sayısı

7-8 arası puan verenler pasiflerdir. NPS'yi şikayet nedenlerine göre dağılım gibi çeşitli kategorilere göre derinlemesine inceleyebiliriz.

In [39]:
self_ser_cat_1

       order_id          order_time order_city  order_area order_kitchen  order_restaurant_id  order_size_TRY preffered_payment_method  isSeamless  isnotSeamless                      contact_reason_CSRLevel3 contact_reason_MainGroup  isContact  isSelfService  ContactCSAT  SelfServiceCSAT  NPS-Q-Score
49      2180498 2024-04-29 06:33:40   İstanbul     Beyoğlu         Pizza               876865             354        Credit/Debit Card           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            6
164     3321365 2024-08-30 19:01:22   İstanbul    Ümraniye        Burger               676328             417                     Cash           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            5
169     6291085 2024-08-08 19:44:11   İstanbul    Esenyurt    Soğuk Meze               534232             164        Credit/Debit Card           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            5
208     2700831 2024-03-14 03:06:54   İstanbul     Üsküdar      Kahvaltı               315151             528           Online Payment           0              1                 Complaint about extreme delay              Order Delay          0              1            0                1            8
280     8348059 2024-07-07 18:15:32   İstanbul    Çekmeköy          Pide               231209              97           Online Payment           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            2
...         ...                 ...        ...         ...           ...                  ...             ...                      ...         ...            ...                                           ...                      ...        ...            ...          ...              ...          ...
49914   5569721 2024-05-19 20:25:00   İstanbul  Sultangazi  Ev Yemekleri               921077             564        Credit/Debit Card           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            8
49929   5377498 2024-03-03 14:57:46   İstanbul     Üsküdar         Tatlı               975629              80           Online Payment           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            8
49956   4724098 2024-06-18 03:32:46   İstanbul    Çekmeköy          Pide               230292             191           Online Payment           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            5
49962   3945270 2024-01-02 05:22:40   İstanbul     Kadıköy         Pizza               780135             504        Credit/Debit Card           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            9
49982   6922966 2024-03-15 14:02:54   İstanbul    Güngören        Burger               160881             248           Online Payment           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            6

[1813 rows x 17 columns]

In [40]:
self_ser_cat_1["contact_reason_CSRLevel3"].value_counts()

Complaint about severe delay                    438
Complaint about moderate delay                  376
Order marked as delivered but didn't receive    354
Restaurant hasn't started preparing the food    345
Complaint about extreme delay                   300
Name: contact_reason_CSRLevel3, dtype: int64

In [41]:
def cat_summary(dataframe, col_name):
    print(pd.DataFrame({col_name: dataframe[col_name].value_counts(),
                        "% ORAN" : 100 * dataframe[col_name].value_counts() / len(dataframe)}))
    print("#################################")
    
cat_summary(self_ser_cat_1, "contact_reason_CSRLevel3")

                                              contact_reason_CSRLevel3     % ORAN
Complaint about severe delay                                       438  24.158853
Complaint about moderate delay                                     376  20.739106
Order marked as delivered but didn't receive                       354  19.525648
Restaurant hasn't started preparing the food                       345  19.029233
Complaint about extreme delay                                      300  16.547159
#################################

In [42]:
self_ser_cat_1["NPS-Q-Score"].value_counts()

8     404
7     298
6     265
5     243
9     171
4     159
3     119
10     74
1      42
2      38
Name: NPS-Q-Score, dtype: int64

In [43]:
cat_summary(self_ser_cat_1, "NPS-Q-Score")

    NPS-Q-Score     % ORAN
8           404  22.283508
7           298  16.436845
6           265  14.616657
5           243  13.403199
9           171   9.431881
4           159   8.769994
3           119   6.563707
10           74   4.081633
1            42   2.316602
2            38   2.095974
#################################

### ŞİKAYETE GÖRE PUANLAMA

selfservis 1 puan 1

In [44]:
# Top 5 alanı buluyoruz
top_5_areas = self_ser_cat_1.groupby('contact_reason_CSRLevel3').size().nlargest(20).index

# Her alan için NPS-Q-Score frekansları ve NPS skorunu hesaplıyoruz
for area in top_5_areas:
    print(f"Order Area: {area}")
    
    # İlgili alan için order_kitchen frekanslarını bul
    kitchen_counts = self_ser_cat_1[self_ser_cat_1['contact_reason_CSRLevel3'] == area]['NPS-Q-Score'].value_counts()
    
    # NPS skoru için verileri ayırıyoruz
    data = self_ser_cat_1[self_ser_cat_1['contact_reason_CSRLevel3'] == area]['NPS-Q-Score']
    total_responses = len(data)
    promoters = len(data[(data >= 9) & (data <= 10)])  # 9-10 puan alanlar
    detractors = len(data[(data >= 1) & (data <= 6)])  # 1-6 puan alanlar
    
    # NPS skorunu hesaplıyoruz
    if total_responses > 0:
        nps_score = (promoters - detractors) / total_responses * 100
    else:
        nps_score = 0

    # En çok kullanılan kitchen değerlerini yazdırıyoruz
    print(kitchen_counts.head(20))  # İlk 20 değeri göstermek için .head() kullanıyoruz
    print(f"Total Promoters: {promoters}")
    print(f"Total Detractors: {detractors}")
    print(f"NPS-SCORE: {nps_score:.2f}%\n")
    print(f"--------------------------------------------")

Order Area: Complaint about severe delay
8     90
6     83
7     66
5     55
9     43
4     41
3     27
10    15
1     12
2      6
Name: NPS-Q-Score, dtype: int64
Total Promoters: 58
Total Detractors: 224
NPS-SCORE: -37.90%

--------------------------------------------
Order Area: Complaint about moderate delay
8     85
5     59
7     58
6     51
4     39
9     35
3     24
10    13
1      6
2      6
Name: NPS-Q-Score, dtype: int64
Total Promoters: 48
Total Detractors: 185
NPS-SCORE: -36.44%

--------------------------------------------
Order Area: Order marked as delivered but didn't receive
8     75
7     59
5     52
9     43
6     41
4     26
10    20
3     19
2     14
1      5
Name: NPS-Q-Score, dtype: int64
Total Promoters: 63
Total Detractors: 157
NPS-SCORE: -26.55%

--------------------------------------------
Order Area: Restaurant hasn't started preparing the food
8     83
7     58
6     52
5     38
4     34
9     26
3     22
1     13
10    13
2      6
Name: NPS-Q-Score, dtype: int64
Total Promoters: 39
Total Detractors: 165
NPS-SCORE: -36.52%

--------------------------------------------
Order Area: Complaint about extreme delay
8     71
7     57
5     39
6     38
3     27
9     24
4     19
10    13
1      6
2      6
Name: NPS-Q-Score, dtype: int64
Total Promoters: 37
Total Detractors: 135
NPS-SCORE: -32.67%

--------------------------------------------

#### selfservis 1 puan 2

In [45]:
# Top 5 alanı buluyoruz
top_5_areas = self_ser_cat_2.groupby('contact_reason_CSRLevel3').size().nlargest(5).index

# Her alan için NPS-Q-Score frekansları ve NPS skorunu hesaplıyoruz
for area in top_5_areas:
    print(f"Order Area: {area}")
    
    # İlgili alan için order_kitchen frekanslarını bul
    kitchen_counts = self_ser_cat_2[self_ser_cat_2['contact_reason_CSRLevel3'] == area]['NPS-Q-Score'].value_counts()
    
    # NPS skoru için verileri ayırıyoruz
    data = self_ser_cat_2[self_ser_cat_2['contact_reason_CSRLevel3'] == area]['NPS-Q-Score']
    total_responses = len(data)
    promoters = len(data[(data >= 9) & (data <= 10)])  # 9-10 puan alanlar
    detractors = len(data[(data >= 1) & (data <= 6)])  # 1-6 puan alanlar
    
    # NPS skorunu hesaplıyoruz
    if total_responses > 0:
        nps_score = (promoters - detractors) / total_responses * 100
    else:
        nps_score = 0

    # En çok kullanılan kitchen değerlerini yazdırıyoruz
    print(kitchen_counts.head(20))  # İlk 20 değeri göstermek için .head() kullanıyoruz
    print(f"Total Promoters: {promoters}")
    print(f"Total Detractors: {detractors}")
    print(f"NPS-SCORE: {nps_score:.2f}%\n")
    print(f"--------------------------------------------")

Order Area: Complaint about severe delay
8     104
7      73
6      70
5      68
9      47
4      35
3      34
10     23
1      13
2       7
Name: NPS-Q-Score, dtype: int64
Total Promoters: 70
Total Detractors: 227
NPS-SCORE: -33.12%

--------------------------------------------
Order Area: Order marked as delivered but didn't receive
8     80
7     67
6     61
5     52
9     49
4     31
3     23
10    18
2     10
1      7
Name: NPS-Q-Score, dtype: int64
Total Promoters: 67
Total Detractors: 184
NPS-SCORE: -29.40%

--------------------------------------------
Order Area: Restaurant hasn't started preparing the food
8     85
6     65
7     59
5     51
9     32
4     31
10    14
3     14
1     12
2      7
Name: NPS-Q-Score, dtype: int64
Total Promoters: 46
Total Detractors: 180
NPS-SCORE: -36.22%

--------------------------------------------
Order Area: Complaint about moderate delay
8     90
6     62
7     51
5     47
9     28
4     26
3     20
10    19
2     13
1      9
Name: NPS-Q-Score, dtype: int64
Total Promoters: 47
Total Detractors: 177
NPS-SCORE: -35.62%

--------------------------------------------
Order Area: Complaint about extreme delay
8     71
6     52
7     45
5     32
9     31
4     26
3     23
10    19
1     11
2      9
Name: NPS-Q-Score, dtype: int64
Total Promoters: 50
Total Detractors: 153
NPS-SCORE: -32.29%

--------------------------------------------

#### selfservis 1 puan 3

In [46]:
# Top 5 alanı buluyoruz
top_5_areas = self_ser_cat_3.groupby('contact_reason_CSRLevel3').size().nlargest(5).index

# Her alan için NPS-Q-Score frekansları ve NPS skorunu hesaplıyoruz
for area in top_5_areas:
    print(f"Order Area: {area}")
    
    # İlgili alan için order_kitchen frekanslarını bul
    kitchen_counts = self_ser_cat_3[self_ser_cat_3['contact_reason_CSRLevel3'] == area]['NPS-Q-Score'].value_counts()
    
    # NPS skoru için verileri ayırıyoruz
    data = self_ser_cat_3[self_ser_cat_3['contact_reason_CSRLevel3'] == area]['NPS-Q-Score']
    total_responses = len(data)
    promoters = len(data[(data >= 9) & (data <= 10)])  # 9-10 puan alanlar
    detractors = len(data[(data >= 1) & (data <= 6)])  # 1-6 puan alanlar
    
    # NPS skorunu hesaplıyoruz
    if total_responses > 0:
        nps_score = (promoters - detractors) / total_responses * 100
    else:
        nps_score = 0

    # En çok kullanılan kitchen değerlerini yazdırıyoruz
    print(kitchen_counts.head(20))  # İlk 20 değeri göstermek için .head() kullanıyoruz
    print(f"Total Promoters: {promoters}")
    print(f"Total Detractors: {detractors}")
    print(f"NPS-SCORE: {nps_score:.2f}%\n")
    print(f"--------------------------------------------")

Order Area: Missing item
8     44
7     38
6     32
10    28
9     22
5     21
4     10
3      7
1      2
Name: NPS-Q-Score, dtype: int64
Total Promoters: 50
Total Detractors: 72
NPS-SCORE: -10.78%

--------------------------------------------
Order Area: Wrong item
8     46
7     32
6     27
10    25
9     21
4     17
5     15
3      9
2      3
1      1
Name: NPS-Q-Score, dtype: int64
Total Promoters: 46
Total Detractors: 72
NPS-SCORE: -13.27%

--------------------------------------------
Order Area: Request: accidental order
8     35
7     29
10    25
6     18
9     18
5     15
4      7
3      6
1      4
2      1
Name: NPS-Q-Score, dtype: int64
Total Promoters: 43
Total Detractors: 51
NPS-SCORE: -5.06%

--------------------------------------------
Order Area: Request: order is late-does not want to wait
8     32
10    25
9     20
7     18
5     13
6     12
3      7
4      6
2      2
1      2
Name: NPS-Q-Score, dtype: int64
Total Promoters: 45
Total Detractors: 42
NPS-SCORE: 2.19%

--------------------------------------------
Order Area: Request: order will take longer than expected
8     27
10    16
6     16
7     14
9     14
5     11
4      8
3      5
2      1
1      1
Name: NPS-Q-Score, dtype: int64
Total Promoters: 30
Total Detractors: 42
NPS-SCORE: -10.62%

--------------------------------------------

## ZAMAN GÖRE FEATURE ÜRETMEK

In [47]:
self_ser_cat_1

       order_id          order_time order_city  order_area order_kitchen  order_restaurant_id  order_size_TRY preffered_payment_method  isSeamless  isnotSeamless                      contact_reason_CSRLevel3 contact_reason_MainGroup  isContact  isSelfService  ContactCSAT  SelfServiceCSAT  NPS-Q-Score
49      2180498 2024-04-29 06:33:40   İstanbul     Beyoğlu         Pizza               876865             354        Credit/Debit Card           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            6
164     3321365 2024-08-30 19:01:22   İstanbul    Ümraniye        Burger               676328             417                     Cash           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            5
169     6291085 2024-08-08 19:44:11   İstanbul    Esenyurt    Soğuk Meze               534232             164        Credit/Debit Card           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            5
208     2700831 2024-03-14 03:06:54   İstanbul     Üsküdar      Kahvaltı               315151             528           Online Payment           0              1                 Complaint about extreme delay              Order Delay          0              1            0                1            8
280     8348059 2024-07-07 18:15:32   İstanbul    Çekmeköy          Pide               231209              97           Online Payment           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            2
...         ...                 ...        ...         ...           ...                  ...             ...                      ...         ...            ...                                           ...                      ...        ...            ...          ...              ...          ...
49914   5569721 2024-05-19 20:25:00   İstanbul  Sultangazi  Ev Yemekleri               921077             564        Credit/Debit Card           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            8
49929   5377498 2024-03-03 14:57:46   İstanbul     Üsküdar         Tatlı               975629              80           Online Payment           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            8
49956   4724098 2024-06-18 03:32:46   İstanbul    Çekmeköy          Pide               230292             191           Online Payment           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            5
49962   3945270 2024-01-02 05:22:40   İstanbul     Kadıköy         Pizza               780135             504        Credit/Debit Card           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            9
49982   6922966 2024-03-15 14:02:54   İstanbul    Güngören        Burger               160881             248           Online Payment           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            6

[1813 rows x 17 columns]

# SELF SERVİS 1 GÜN İŞEMLERİ

In [48]:
# 'order_time' sütununu datetime formatına çevir
self_ser_cat_1['order_time'] = pd.to_datetime(self_ser_cat_1['order_time'])

# Saniyeleri kaldırarak sadece saat ve dakika kısmını al
self_ser_cat_1['order_time_time'] = self_ser_cat_1['order_time'].dt.strftime('%H:%M')

# 'Date', 'Month', ve 'Year' sütunlarını oluştur
self_ser_cat_1['Date'] = self_ser_cat_1['order_time'].dt.day
self_ser_cat_1['Month'] = self_ser_cat_1['order_time'].dt.month
self_ser_cat_1['Year'] = self_ser_cat_1['order_time'].dt.year

# Gün ismini almak için
self_ser_cat_1['Day_Name'] = self_ser_cat_1['order_time'].dt.day_name()

# Yeni sütunları DataFrame'e ekle, mevcut verileri koruyarak
# Bu adımda 'pd.concat' kullanılmıyor, çünkü zaten 'self_ser_cat_1' içine ekliyoruz

self_ser_cat_1

C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\4198103722.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_1['order_time'] = pd.to_datetime(self_ser_cat_1['order_time'])
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\4198103722.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_1['order_time_time'] = self_ser_cat_1['order_time'].dt.strftime('%H:%M')
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\4198103722.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_1['Date'] = self_ser_cat_1['order_time'].dt.day
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\4198103722.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_1['Month'] = self_ser_cat_1['order_time'].dt.month
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\4198103722.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_1['Year'] = self_ser_cat_1['order_time'].dt.year
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\4198103722.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_1['Day_Name'] = self_ser_cat_1['order_time'].dt.day_name()

       order_id          order_time order_city  order_area order_kitchen  order_restaurant_id  order_size_TRY preffered_payment_method  isSeamless  isnotSeamless                      contact_reason_CSRLevel3 contact_reason_MainGroup  isContact  isSelfService  ContactCSAT  SelfServiceCSAT  NPS-Q-Score order_time_time  Date  Month  Year  Day_Name
49      2180498 2024-04-29 06:33:40   İstanbul     Beyoğlu         Pizza               876865             354        Credit/Debit Card           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            6           06:33    29      4  2024    Monday
164     3321365 2024-08-30 19:01:22   İstanbul    Ümraniye        Burger               676328             417                     Cash           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            5           19:01    30      8  2024    Friday
169     6291085 2024-08-08 19:44:11   İstanbul    Esenyurt    Soğuk Meze               534232             164        Credit/Debit Card           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            5           19:44     8      8  2024  Thursday
208     2700831 2024-03-14 03:06:54   İstanbul     Üsküdar      Kahvaltı               315151             528           Online Payment           0              1                 Complaint about extreme delay              Order Delay          0              1            0                1            8           03:06    14      3  2024  Thursday
280     8348059 2024-07-07 18:15:32   İstanbul    Çekmeköy          Pide               231209              97           Online Payment           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            2           18:15     7      7  2024    Sunday
...         ...                 ...        ...         ...           ...                  ...             ...                      ...         ...            ...                                           ...                      ...        ...            ...          ...              ...          ...             ...   ...    ...   ...       ...
49914   5569721 2024-05-19 20:25:00   İstanbul  Sultangazi  Ev Yemekleri               921077             564        Credit/Debit Card           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            8           20:25    19      5  2024    Sunday
49929   5377498 2024-03-03 14:57:46   İstanbul     Üsküdar         Tatlı               975629              80           Online Payment           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            8           14:57     3      3  2024    Sunday
49956   4724098 2024-06-18 03:32:46   İstanbul    Çekmeköy          Pide               230292             191           Online Payment           0              1                Complaint about moderate delay              Order Delay          0              1            0                1            5           03:32    18      6  2024   Tuesday
49962   3945270 2024-01-02 05:22:40   İstanbul     Kadıköy         Pizza               780135             504        Credit/Debit Card           0              1                  Complaint about severe delay              Order Delay          0              1            0                1            9           05:22     2      1  2024   Tuesday
49982   6922966 2024-03-15 14:02:54   İstanbul    Güngören        Burger               160881             248           Online Payment           0              1  Order marked as delivered but didn't receive              Order Delay          0              1            0                1            6           14:02    15      3  2024    Friday

[1813 rows x 22 columns]

In [49]:
self_ser_cat_1["order_time_time"].value_counts().sort_index(ascending=False) # anlamsız çıktı
self_ser_cat_1["order_time_time"].value_counts() #burası 5 farklı alana göre sınıflandırılıp tekrardan incelenmeli aslında ama
# zaman yok örneğin 05.00 - 10.00, 10.01 - 15.00 ... gibi geçtim direkt

18:09    6
21:04    6
14:11    5
03:32    5
22:16    5
        ..
07:49    1
01:03    1
01:10    1
11:26    1
14:57    1
Name: order_time_time, Length: 1040, dtype: int64

In [50]:
self_ser_cat_1["Date"].value_counts() #en çok 1 puan verme 10u ve 24nde oluyormuş en az ise ayın son günlerinde

10    71
24    71
1     70
14    70
12    68
22    66
3     65
28    64
2     64
11    64
19    64
26    61
5     60
17    60
25    58
18    57
15    57
23    57
21    57
16    56
30    56
13    55
7     55
27    54
9     53
29    53
20    52
8     51
6     49
4     48
31    27
Name: Date, dtype: int64

In [51]:
self_ser_cat_1["Month"].value_counts() # genel olarak her ay ortalama bu şekilde oluyormuş ancak haziran ayında az olmuş ağusyot
# daha bitmedi o yüzden az olabilri.

1    240
5    240
4    236
3    233
2    229
7    219
6    210
8    206
Name: Month, dtype: int64

In [52]:
self_ser_cat_1["Day_Name"].value_counts() #en çok çarşamba günleri 1 puan veriliyormuş en az cuma günleri acaba neden diyorum?

Wednesday    298
Sunday       263
Tuesday      257
Saturday     250
Monday       249
Thursday     249
Friday       247
Name: Day_Name, dtype: int64

In [53]:
self_ser_cat_1["contact_reason_CSRLevel3"].value_counts() #1.ciyi seçiyorum

Complaint about severe delay                    438
Complaint about moderate delay                  376
Order marked as delivered but didn't receive    354
Restaurant hasn't started preparing the food    345
Complaint about extreme delay                   300
Name: contact_reason_CSRLevel3, dtype: int64

In [54]:
def gune_gore_problem(problem):
    
    gun_problem = self_ser_cat_1[self_ser_cat_1["contact_reason_CSRLevel3"] == problem]["Day_Name"].value_counts()
    
    return gun_problem

In [55]:
gune_gore_problem("Complaint about severe delay")

Wednesday    74
Tuesday      71
Sunday       68
Saturday     65
Monday       62
Friday       51
Thursday     47
Name: Day_Name, dtype: int64

#### self servis 1 puan 1 olup problemlere göre en çok hangi günlerde oluyor

In [56]:
def gune_gore_problem(st, problem):
    # 'problem' değerine sahip olan kayıtları filtrele
    gun_problem = st[st["contact_reason_CSRLevel3"] == problem]["Day_Name"].value_counts()
    
    # Gün isimlerine göre problem sayısını döndür
    return gun_problem

# 'contact_reason_CSRLevel3' sütunundaki her bir değer için fonksiyonu çağır
for problem in self_ser_cat_1["contact_reason_CSRLevel3"].unique():
    print(f"Problem: {problem}")
    print(gune_gore_problem(self_ser_cat_1, problem))
    print("\n")

Problem: Complaint about moderate delay
Friday       63
Sunday       59
Wednesday    57
Thursday     56
Monday       52
Saturday     45
Tuesday      44
Name: Day_Name, dtype: int64


Problem: Order marked as delivered but didn't receive
Sunday       56
Wednesday    55
Thursday     54
Saturday     51
Friday       51
Tuesday      50
Monday       37
Name: Day_Name, dtype: int64


Problem: Complaint about extreme delay
Wednesday    50
Thursday     48
Monday       47
Tuesday      47
Saturday     38
Sunday       38
Friday       32
Name: Day_Name, dtype: int64


Problem: Complaint about severe delay
Wednesday    74
Tuesday      71
Sunday       68
Saturday     65
Monday       62
Friday       51
Thursday     47
Name: Day_Name, dtype: int64


Problem: Restaurant hasn't started preparing the food
Wednesday    62
Saturday     51
Monday       51
Friday       50
Tuesday      45
Thursday     44
Sunday       42
Name: Day_Name, dtype: int64

# SELF SERVİS 2 GÜN İŞEMLERİ

### self servis 1 puan 2 olup problemlere göre en çok hangi günlerde oluyor

In [57]:
# 'order_time' sütununu datetime formatına çevir
self_ser_cat_2['order_time'] = pd.to_datetime(self_ser_cat_2['order_time'])

# Saniyeleri kaldırarak sadece saat ve dakika kısmını al
self_ser_cat_2['order_time_time'] = self_ser_cat_2['order_time'].dt.strftime('%H:%M')

# 'Date', 'Month', ve 'Year' sütunlarını oluştur
self_ser_cat_2['Date'] = self_ser_cat_2['order_time'].dt.day
self_ser_cat_2['Month'] = self_ser_cat_2['order_time'].dt.month
self_ser_cat_2['Year'] = self_ser_cat_2['order_time'].dt.year

# Gün ismini almak için
self_ser_cat_2['Day_Name'] = self_ser_cat_2['order_time'].dt.day_name()

# Yeni sütunları DataFrame'e ekle, mevcut verileri koruyarak
# Bu adımda 'pd.concat' kullanılmıyor, çünkü zaten 'self_ser_cat_1' içine ekliyoruz

self_ser_cat_2

C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\2500373330.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_2['order_time'] = pd.to_datetime(self_ser_cat_2['order_time'])
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\2500373330.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_2['order_time_time'] = self_ser_cat_2['order_time'].dt.strftime('%H:%M')
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\2500373330.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_2['Date'] = self_ser_cat_2['order_time'].dt.day
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\2500373330.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_2['Month'] = self_ser_cat_2['order_time'].dt.month
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\2500373330.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_2['Year'] = self_ser_cat_2['order_time'].dt.year
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\2500373330.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_2['Day_Name'] = self_ser_cat_2['order_time'].dt.day_name()

       order_id          order_time order_city  order_area order_kitchen  order_restaurant_id  order_size_TRY preffered_payment_method  isSeamless  isnotSeamless                      contact_reason_CSRLevel3             contact_reason_MainGroup  isContact  isSelfService  ContactCSAT  SelfServiceCSAT  NPS-Q-Score order_time_time  Date  Month  Year   Day_Name
13      6638263 2024-04-17 11:31:39   İstanbul    Bakırköy         Döner               611084             280           Online Payment           0              1  Order marked as delivered but didn't receive                          Order Delay          0              1            0                2            9           11:31    17      4  2024  Wednesday
16      3428331 2024-04-14 11:50:43   İstanbul  Bayrampaşa        Burger               138139             609           Online Payment           0              1                                    Wrong item      Missing Item & Wrong Item/Order          0              1            0                2            7           11:50    14      4  2024     Sunday
25      3453042 2024-03-14 14:36:10   İstanbul     Maltepe      Çiğköfte                76044             696           Online Payment           0              1                                  Food quality    Product & Service Dissatisfaction          0              1            0                2            8           14:36    14      3  2024   Thursday
27      4615200 2024-04-03 00:58:21   İstanbul    Beşiktaş        Burger               512524             529           Online Payment           0              1                                    Food items  Adding Note & Delivery Instructions          0              1            0                2            9           00:58     3      4  2024  Wednesday
72      7090464 2024-05-23 10:15:07   İstanbul    Güngören          Pide               152329             656           Online Payment           0              1  Order marked as delivered but didn't receive                          Order Delay          0              1            0                2            9           10:15    23      5  2024   Thursday
...         ...                 ...        ...         ...           ...                  ...             ...                      ...         ...            ...                                           ...                                  ...        ...            ...          ...              ...          ...             ...   ...    ...   ...        ...
49916   9936276 2024-08-21 10:46:33   İstanbul       Fatih         Pizza               767308             410           Online Payment           0              1                                  Food quality    Product & Service Dissatisfaction          0              1            0                2            8           10:46    21      8  2024  Wednesday
49918   6711857 2024-05-15 05:21:00   İstanbul     Kadıköy         Tatlı               438824             207           Online Payment           0              1  Restaurant hasn't started preparing the food                          Order Delay          0              1            0                2            8           05:21    15      5  2024  Wednesday
49943    953249 2024-02-26 18:35:01   İstanbul  Sultangazi          Pide               152714             565           Online Payment           0              1            Request: Partner closed for pickup                Cancellation Requests          0              1            0                2            6           18:35    26      2  2024     Monday
49959   4760602 2024-07-28 00:35:10   İstanbul       Şişli        Burger               202047             565                     Cash           0              1  Order marked as delivered but didn't receive                          Order Delay          0              1            0                2            7           00:35    28      7  2024     Sunday
49981   1893023 2024-01-02 22:19:01   İstanbul        Şile  Ev Yemekleri               325125             351                     Cash           0              1                     Request: accidental order                Cancellation Requests          0              1            0                2            2           22:19     2      1  2024    Tuesday

[3552 rows x 22 columns]

In [58]:
self_ser_cat_2["order_time_time"].value_counts().sort_index(ascending=False) # anlamsız çıktı
self_ser_cat_2["order_time_time"].value_counts() # saat işlemleri anlamsız gibi

04:21    8
12:53    8
14:24    8
14:03    8
12:40    7
        ..
21:58    1
10:58    1
10:37    1
09:31    1
23:09    1
Name: order_time_time, Length: 1333, dtype: int64

In [59]:
self_ser_cat_2["Date"].value_counts() #en çok 1 puan verme yine ayın 10u ve 22nde oluyormuş en az ise ayın son günlerinde bu sonuçlara 
# göre ayın onu ve 20 sinin ilk haftası problem var gibi duruyor

22    138
10    134
25    129
4     129
9     126
5     126
3     125
28    124
1     121
17    121
7     120
24    119
20    118
11    118
27    117
23    116
13    116
21    115
12    113
16    112
19    112
29    112
30    109
26    108
2     106
14    103
15    103
8     101
18    100
6      96
31     65
Name: Date, dtype: int64

In [60]:
self_ser_cat_2["Month"].value_counts() # genel olarak her ay ortalama bu şekilde oluyormuş ancak haziran ayında az olmuş ağusyot
# daha bitmedi o yüzden az olabilri.

3    475
5    465
7    462
1    447
2    437
6    430
4    418
8    418
Name: Month, dtype: int64

In [61]:
self_ser_cat_2["Day_Name"].value_counts() #çok da fark çıkmadı ama incelenebilir keyfi

Saturday     518
Thursday     513
Monday       512
Tuesday      505
Sunday       504
Friday       501
Wednesday    499
Name: Day_Name, dtype: int64

In [62]:
self_ser_cat_2["contact_reason_CSRLevel3"].value_counts() #1.ciyi seçiyorum

Complaint about severe delay                     474
Order marked as delivered but didn't receive     398
Restaurant hasn't started preparing the food     370
Complaint about moderate delay                   365
Complaint about extreme delay                    319
Missing item                                     227
Wrong item                                       211
Request: order is late-does not want to wait     153
Request: accidental order                        143
Food quality                                     125
Request: order will take longer than expected    122
Partner cancellation                              78
Spilled food                                      68
Food temperature                                  60
Request: voucher not applied                      49
Request: changed mind                             49
Request: Partner closed for pickup                48
Cooking instructions were not followed            44
Delivery instructions                             44
Request: duplicated order                         39
Cooking instructions                              25
Invoice missing                                   24
Food items                                        23
Address                                           23
Payment method                                    19
Information request                               18
Delivery time/date                                18
Inappropriate behaviour                           16
Name: contact_reason_CSRLevel3, dtype: int64

In [63]:
def gune_gore_problem(problem):
    
    gun_problem = self_ser_cat_2[self_ser_cat_2["contact_reason_CSRLevel3"] == problem]["Day_Name"].value_counts()
    
    return gun_problem

gune_gore_problem("Complaint about severe delay")

Monday       82
Saturday     71
Tuesday      67
Sunday       67
Thursday     66
Wednesday    64
Friday       57
Name: Day_Name, dtype: int64

#### self servis 1 puan 2 olup problemlere göre en çok hangi günlerde oluyor

In [64]:
def gune_gore_problem(st, problem):
    # 'problem' değerine sahip olan kayıtları filtrele
    gun_problem = st[st["contact_reason_CSRLevel3"] == problem]["Day_Name"].value_counts()
    
    # Gün isimlerine göre problem sayısını döndür
    return gun_problem

# 'contact_reason_CSRLevel3' sütunundaki her bir değer için fonksiyonu çağır
for problem in self_ser_cat_2["contact_reason_CSRLevel3"].unique():
    print(f"Problem: {problem}")
    print(gune_gore_problem(self_ser_cat_2, problem))
    print("\n")

Problem: Order marked as delivered but didn't receive
Thursday     65
Saturday     65
Friday       58
Sunday       58
Wednesday    55
Tuesday      49
Monday       48
Name: Day_Name, dtype: int64


Problem: Wrong item
Friday       35
Tuesday      33
Monday       32
Wednesday    30
Saturday     29
Thursday     28
Sunday       24
Name: Day_Name, dtype: int64


Problem: Food quality
Sunday       21
Saturday     21
Thursday     20
Wednesday    19
Monday       17
Tuesday      14
Friday       13
Name: Day_Name, dtype: int64


Problem: Food items
Sunday       6
Tuesday      5
Saturday     4
Friday       4
Wednesday    3
Thursday     1
Name: Day_Name, dtype: int64


Problem: Complaint about extreme delay
Monday       55
Tuesday      50
Saturday     45
Wednesday    45
Sunday       42
Thursday     42
Friday       40
Name: Day_Name, dtype: int64


Problem: Request: order is late-does not want to wait
Monday       25
Friday       23
Tuesday      22
Thursday     21
Sunday       21
Wednesday    21
Saturday     20
Name: Day_Name, dtype: int64


Problem: Complaint about severe delay
Monday       82
Saturday     71
Tuesday      67
Sunday       67
Thursday     66
Wednesday    64
Friday       57
Name: Day_Name, dtype: int64


Problem: Spilled food
Sunday       12
Saturday     11
Tuesday      11
Wednesday    10
Monday       10
Thursday      8
Friday        6
Name: Day_Name, dtype: int64


Problem: Complaint about moderate delay
Thursday     62
Saturday     55
Wednesday    52
Sunday       51
Tuesday      50
Friday       48
Monday       47
Name: Day_Name, dtype: int64


Problem: Cooking instructions were not followed
Tuesday      10
Monday        9
Saturday      7
Friday        6
Wednesday     5
Thursday      4
Sunday        3
Name: Day_Name, dtype: int64


Problem: Request: duplicated order
Tuesday      8
Monday       8
Saturday     6
Wednesday    5
Friday       5
Sunday       4
Thursday     3
Name: Day_Name, dtype: int64


Problem: Request: order will take longer than expected
Sunday       23
Friday       20
Saturday     19
Thursday     18
Tuesday      16
Wednesday    14
Monday       12
Name: Day_Name, dtype: int64


Problem: Restaurant hasn't started preparing the food
Friday       73
Sunday       61
Wednesday    56
Tuesday      50
Thursday     49
Saturday     43
Monday       38
Name: Day_Name, dtype: int64


Problem: Food temperature
Tuesday      11
Monday       11
Wednesday    10
Saturday      8
Friday        8
Sunday        7
Thursday      5
Name: Day_Name, dtype: int64


Problem: Partner cancellation
Monday       14
Sunday       13
Saturday     12
Thursday     12
Wednesday    10
Friday        9
Tuesday       8
Name: Day_Name, dtype: int64


Problem: Missing item
Sunday       36
Saturday     36
Thursday     36
Wednesday    32
Tuesday      30
Monday       29
Friday       28
Name: Day_Name, dtype: int64


Problem: Request: voucher not applied
Friday       11
Thursday      9
Sunday        8
Monday        7
Wednesday     6
Tuesday       5
Saturday      3
Name: Day_Name, dtype: int64


Problem: Request: changed mind
Saturday     10
Monday        9
Thursday      8
Wednesday     7
Friday        7
Sunday        4
Tuesday       4
Name: Day_Name, dtype: int64


Problem: Inappropriate behaviour
Saturday     4
Monday       3
Thursday     3
Friday       2
Sunday       2
Tuesday      1
Wednesday    1
Name: Day_Name, dtype: int64


Problem: Request: Partner closed for pickup
Tuesday      11
Wednesday     9
Monday        8
Sunday        7
Friday        6
Saturday      4
Thursday      3
Name: Day_Name, dtype: int64


Problem: Information request
Sunday       5
Wednesday    4
Thursday     3
Monday       2
Tuesday      2
Friday       2
Name: Day_Name, dtype: int64


Problem: Request: accidental order
Thursday     27
Saturday     26
Monday       22
Tuesday      18
Wednesday    18
Sunday       16
Friday       16
Name: Day_Name, dtype: int64


Problem: Payment method
Thursday     5
Friday       4
Tuesday      4
Monday       3
Wednesday    2
Sunday       1
Name: Day_Name, dtype: int64


Problem: Cooking instructions
Friday       6
Tuesday      4
Thursday     4
Wednesday    4
Sunday       3
Saturday     3
Monday       1
Name: Day_Name, dtype: int64


Problem: Invoice missing
Monday       5
Saturday     4
Thursday     4
Sunday       4
Friday       4
Wednesday    2
Tuesday      1
Name: Day_Name, dtype: int64


Problem: Delivery instructions
Wednesday    11
Tuesday      10
Monday        8
Saturday      5
Friday        4
Thursday      3
Sunday        3
Name: Day_Name, dtype: int64


Problem: Address
Tuesday      9
Saturday     4
Monday       3
Friday       3
Sunday       2
Wednesday    1
Thursday     1
Name: Day_Name, dtype: int64


Problem: Delivery time/date
Monday       4
Friday       3
Saturday     3
Thursday     3
Wednesday    3
Tuesday      2
Name: Day_Name, dtype: int64

# SELF SERVİS 3 GÜN İŞEMLERİ

### self servis 1 puan 3 olup problemlere göre en çok hangi günlerde oluyor

In [65]:
# 'order_time' sütununu datetime formatına çevir
self_ser_cat_3['order_time'] = pd.to_datetime(self_ser_cat_3['order_time'])

# Saniyeleri kaldırarak sadece saat ve dakika kısmını al
self_ser_cat_3['order_time_time'] = self_ser_cat_3['order_time'].dt.strftime('%H:%M')

# 'Date', 'Month', ve 'Year' sütunlarını oluştur
self_ser_cat_3['Date'] = self_ser_cat_3['order_time'].dt.day
self_ser_cat_3['Month'] = self_ser_cat_3['order_time'].dt.month
self_ser_cat_3['Year'] = self_ser_cat_3['order_time'].dt.year

# Gün ismini almak için
self_ser_cat_3['Day_Name'] = self_ser_cat_3['order_time'].dt.day_name()

# Yeni sütunları DataFrame'e ekle, mevcut verileri koruyarak
# Bu adımda 'pd.concat' kullanılmıyor, çünkü zaten 'self_ser_cat_1' içine ekliyoruz

self_ser_cat_3

C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\236550687.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_3['order_time'] = pd.to_datetime(self_ser_cat_3['order_time'])
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\236550687.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_3['order_time_time'] = self_ser_cat_3['order_time'].dt.strftime('%H:%M')
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\236550687.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_3['Date'] = self_ser_cat_3['order_time'].dt.day
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\236550687.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_3['Month'] = self_ser_cat_3['order_time'].dt.month
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\236550687.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_3['Year'] = self_ser_cat_3['order_time'].dt.year
C:\Users\ytaslioglu\AppData\Local\Temp\ipykernel_53416\236550687.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self_ser_cat_3['Day_Name'] = self_ser_cat_3['order_time'].dt.day_name()

       order_id          order_time order_city     order_area order_kitchen  order_restaurant_id  order_size_TRY preffered_payment_method  isSeamless  isnotSeamless                      contact_reason_CSRLevel3             contact_reason_MainGroup  isContact  isSelfService  ContactCSAT  SelfServiceCSAT  NPS-Q-Score order_time_time  Date  Month  Year   Day_Name
36      1798963 2024-06-02 16:49:54   İstanbul  Gaziosmanpaşa          Pide               610157             458        Credit/Debit Card           0              1                                  Missing item      Missing Item & Wrong Item/Order          0              1            0                3            9           16:49     2      6  2024     Sunday
114     6612933 2024-03-20 02:26:44   İstanbul        Silivri         Döner                68771             337        Credit/Debit Card           0              1                                Payment method  Adding Note & Delivery Instructions          0              1            0                3            5           02:26    20      3  2024  Wednesday
128     3297594 2024-07-27 14:03:08   İstanbul     Bayrampaşa         Pizza               785785             433           Online Payment           0              1  Request: order is late-does not want to wait                Cancellation Requests          0              1            0                3            9           14:03    27      7  2024   Saturday
151     3926003 2024-01-04 18:37:00   İstanbul     Bayrampaşa          Pide               352187             631           Online Payment           0              1                                  Spilled food    Product & Service Dissatisfaction          0              1            0                3            5           18:37     4      1  2024   Thursday
157     1678561 2024-01-18 20:22:40   İstanbul     Bayrampaşa         Tatlı               899571             145           Online Payment           0              1                                  Missing item      Missing Item & Wrong Item/Order          0              1            0                3            6           20:22    18      1  2024   Thursday
...         ...                 ...        ...            ...           ...                  ...             ...                      ...         ...            ...                                           ...                                  ...        ...            ...          ...              ...          ...             ...   ...    ...   ...        ...
49859   6435497 2024-06-12 23:55:51   İstanbul        Kadıköy          Pide               584692             446           Online Payment           0              1  Request: order is late-does not want to wait                Cancellation Requests          0              1            0                3            8           23:55    12      6  2024  Wednesday
49865   3904505 2024-04-27 19:12:42   İstanbul        Avcılar      Kahvaltı               991349             548                Meal Card           0              1                                  Food quality    Product & Service Dissatisfaction          0              1            0                3            8           19:12    27      4  2024   Saturday
49920   5340713 2024-03-19 07:32:48   İstanbul         Pendik          Pide               489608             122           Online Payment           0              1                                  Food quality    Product & Service Dissatisfaction          0              1            0                3            3           07:32    19      3  2024    Tuesday
49946   2882890 2024-05-01 09:21:11   İstanbul        Silivri      Çiğköfte               571902             479           Online Payment           0              1                                    Wrong item      Missing Item & Wrong Item/Order          0              1            0                3            5           09:21     1      5  2024  Wednesday
49979   2586508 2024-04-23 11:21:46   İstanbul        Silivri        Burger                97267             167                Meal Card           0              1                          Partner cancellation                        Other Reasons          0              1            0                3            7           11:21    23      4  2024    Tuesday

[1550 rows x 22 columns]

In [66]:
self_ser_cat_3["order_time_time"].value_counts().sort_index(ascending=False) # anlamsız çıktı
self_ser_cat_3["order_time_time"].value_counts() # saat işlemleri anlamsız gibi

13:58    5
08:18    5
05:02    4
08:44    4
07:39    4
        ..
07:51    1
19:09    1
09:38    1
08:45    1
11:21    1
Name: order_time_time, Length: 962, dtype: int64

In [67]:
self_ser_cat_3["Date"].value_counts() #ayın 18  en fazla

18    62
24    60
13    59
12    59
27    58
21    57
25    57
16    56
4     55
14    53
9     53
29    53
10    52
1     52
6     52
28    51
19    49
15    49
17    49
20    47
5     47
22    46
8     46
7     46
26    46
30    45
11    45
23    42
2     41
3     38
31    25
Name: Date, dtype: int64

In [68]:
self_ser_cat_3["Month"].value_counts() # yine ortalama çıktı

1    208
2    201
4    195
3    193
7    191
8    190
5    187
6    185
Name: Month, dtype: int64

In [69]:
self_ser_cat_3["Day_Name"].value_counts() #çok da fark çıkmadı ama incelenebilir keyfi

Tuesday      234
Monday       234
Sunday       231
Wednesday    221
Saturday     211
Thursday     210
Friday       209
Name: Day_Name, dtype: int64

In [70]:
self_ser_cat_3["contact_reason_CSRLevel3"].value_counts() #1.ciyi seçiyorum

Missing item                                     204
Wrong item                                       196
Request: accidental order                        158
Request: order is late-does not want to wait     137
Request: order will take longer than expected    113
Food quality                                     110
Partner cancellation                              73
Spilled food                                      68
Food temperature                                  64
Cooking instructions were not followed            49
Delivery instructions                             48
Request: voucher not applied                      45
Request: changed mind                             42
Request: Partner closed for pickup                39
Request: duplicated order                         32
Food items                                        26
Payment method                                    25
Cooking instructions                              24
Inappropriate behaviour                           22
Information request                               20
Delivery time/date                                20
Invoice missing                                   19
Address                                           16
Name: contact_reason_CSRLevel3, dtype: int64

In [71]:
def gune_gore_problem(problem):
    
    gun_problem = self_ser_cat_3[self_ser_cat_3["contact_reason_CSRLevel3"] == problem]["Day_Name"].value_counts()
    
    return gun_problem

gune_gore_problem("Missing item")

Monday       35
Wednesday    33
Sunday       29
Thursday     29
Friday       26
Saturday     26
Tuesday      26
Name: Day_Name, dtype: int64

#### self servis 1 puan 3 olup problemlere göre en çok hangi günlerde oluyor

In [72]:
def gune_gore_problem(st, problem):
    # 'problem' değerine sahip olan kayıtları filtrele
    gun_problem = st[st["contact_reason_CSRLevel3"] == problem]["Day_Name"].value_counts()
    
    # Gün isimlerine göre problem sayısını döndür
    return gun_problem

# 'contact_reason_CSRLevel3' sütunundaki her bir değer için fonksiyonu çağır
for problem in self_ser_cat_3["contact_reason_CSRLevel3"].unique():
    print(f"Problem: {problem}")
    print(gune_gore_problem(self_ser_cat_3, problem))
    print("\n")

Problem: Missing item
Monday       35
Wednesday    33
Sunday       29
Thursday     29
Friday       26
Saturday     26
Tuesday      26
Name: Day_Name, dtype: int64


Problem: Payment method
Friday       6
Saturday     5
Sunday       4
Monday       3
Tuesday      3
Wednesday    2
Thursday     2
Name: Day_Name, dtype: int64


Problem: Request: order is late-does not want to wait
Sunday       25
Saturday     22
Wednesday    22
Friday       21
Tuesday      20
Monday       14
Thursday     13
Name: Day_Name, dtype: int64


Problem: Spilled food
Tuesday      12
Sunday       11
Monday       11
Thursday     10
Wednesday    10
Saturday      9
Friday        5
Name: Day_Name, dtype: int64


Problem: Request: accidental order
Tuesday      32
Sunday       25
Monday       25
Thursday     21
Friday       20
Wednesday    20
Saturday     15
Name: Day_Name, dtype: int64


Problem: Request: Partner closed for pickup
Sunday       7
Monday       6
Friday       6
Wednesday    5
Saturday     5
Tuesday      5
Thursday     5
Name: Day_Name, dtype: int64


Problem: Partner cancellation
Saturday     16
Tuesday      11
Wednesday    11
Sunday       11
Thursday     10
Friday        8
Monday        6
Name: Day_Name, dtype: int64


Problem: Request: order will take longer than expected
Monday       24
Thursday     20
Friday       17
Wednesday    16
Tuesday      15
Sunday       11
Saturday     10
Name: Day_Name, dtype: int64


Problem: Request: voucher not applied
Monday       10
Friday        9
Sunday        8
Tuesday       6
Saturday      5
Thursday      4
Wednesday     3
Name: Day_Name, dtype: int64


Problem: Address
Sunday       6
Thursday     3
Friday       3
Tuesday      2
Wednesday    2
Name: Day_Name, dtype: int64


Problem: Invoice missing
Wednesday    5
Friday       4
Saturday     3
Monday       2
Thursday     2
Sunday       2
Tuesday      1
Name: Day_Name, dtype: int64


Problem: Food items
Saturday     5
Thursday     5
Friday       4
Wednesday    4
Tuesday      4
Monday       2
Sunday       2
Name: Day_Name, dtype: int64


Problem: Cooking instructions were not followed
Thursday     11
Wednesday    11
Saturday      7
Sunday        6
Monday        5
Tuesday       5
Friday        4
Name: Day_Name, dtype: int64


Problem: Cooking instructions
Wednesday    6
Friday       5
Sunday       4
Monday       4
Saturday     3
Thursday     1
Tuesday      1
Name: Day_Name, dtype: int64


Problem: Information request
Tuesday      6
Monday       4
Saturday     3
Sunday       3
Thursday     3
Wednesday    1
Name: Day_Name, dtype: int64


Problem: Inappropriate behaviour
Monday       7
Friday       6
Sunday       5
Wednesday    3
Saturday     1
Name: Day_Name, dtype: int64


Problem: Food quality
Saturday     24
Monday       18
Wednesday    15
Friday       15
Thursday     14
Sunday       14
Tuesday      10
Name: Day_Name, dtype: int64


Problem: Request: duplicated order
Sunday       8
Tuesday      5
Saturday     5
Wednesday    4
Monday       4
Friday       4
Thursday     2
Name: Day_Name, dtype: int64


Problem: Food temperature
Friday       11
Thursday     10
Tuesday      10
Wednesday     9
Monday        9
Sunday        8
Saturday      7
Name: Day_Name, dtype: int64


Problem: Delivery instructions
Monday       12
Wednesday     8
Sunday        7
Friday        7
Tuesday       5
Saturday      5
Thursday      4
Name: Day_Name, dtype: int64


Problem: Wrong item
Tuesday      44
Thursday     29
Monday       27
Wednesday    26
Sunday       25
Saturday     24
Friday       21
Name: Day_Name, dtype: int64


Problem: Request: changed mind
Saturday     9
Friday       7
Tuesday      7
Thursday     6
Wednesday    5
Sunday       5
Monday       3
Name: Day_Name, dtype: int64


Problem: Delivery time/date
Thursday    6
Sunday      5
Tuesday     4
Monday      3
Saturday    2
Name: Day_Name, dtype: int64